extension Strings {
    static let it: [String: String] = [
        "menu.settings": "Impostazioni…",
        "menu.about": "Informazioni su Vitrin",
        "menu.showNow": "Mostra le finestre ora",
        "menu.accessibility": "Impostazioni di accessibilità",
        "menu.screenRecording": "Impostazioni di registrazione schermo",
        "menu.retryTap": "Riprova l'ascolto della tastiera",
        "menu.quit": "Esci",
        "status.ax": "Accessibilità",
        "status.sr": "Registrazione schermo",
        "status.tap": "Ascolto",

        "tab.general": "Generali",
        "tab.appearance": "Aspetto",
        "tab.motion": "Movimento",
        "tab.glass": "Vetro",
        "tab.transition": "Transizione",
        "tab.about": "Informazioni",

        "general.trigger": "Tasto di attivazione",
        "general.trigger.note": "Tieni premuto questo tasto e premi Tab. Sulle tastiere con layout PC il tasto Alt fisico invia di solito Command.",
        "general.language": "Lingua",
        "general.login": "Avvia al login",
        "general.login.approval": "macOS attende la tua conferma: apri Impostazioni di Sistema › Generali › Elementi login e attiva Vitrin.",
        "general.login.note": "Vitrin si avvia in background al login; non si apre alcuna finestra.",
        "general.minimized": "Elenca le finestre ridotte a icona",
        "general.titles": "Mostra i titoli delle finestre",
        "general.footer": "Mostra la barra dei suggerimenti",
        "general.icon": "Mostra l'icona nella barra dei menu",
        "general.icon.note": "Con l'icona nascosta puoi raggiungere le impostazioni in tre modi: premere la virgola mentre il selettore è aperto, riaprire Vitrin dal Finder, oppure eseguire open -a Vitrin.",
        "general.hide.title": "Nascondere l'icona nella barra dei menu?",
        "general.hide.body": "Senza icona puoi raggiungere le impostazioni così:\n\n• Premi la virgola ( , ) mentre il selettore è aperto\n• Riapri Vitrin dal Finder\n• Esegui: open -a Vitrin\n\nUsa il pulsante in fondo a questa finestra per uscire.",
        "general.hide.ok": "Nascondi",

        "appearance.layout": "Disposizione",
        "appearance.entrance": "Entrata",
        "appearance.cellWidth": "Larghezza scheda",
        "appearance.thumbHeight": "Altezza anteprima",
        "appearance.columns": "Colonne max",
        "appearance.rows": "Righe max",
        "appearance.material": "Sfondo",
        "appearance.opacity": "Trasparenza del pannello",
        "appearance.shadow": "Ombra del pannello",
        "appearance.corner": "Raggio degli angoli",
        "appearance.op.zero": "Completamente trasparente: le schede fluttuano direttamente sulla scrivania.",
        "appearance.op.mid": "Semitrasparente; le finestre dietro restano leggibili.",
        "appearance.op.full": "Materiale pieno: la scelta più leggibile.",

        "motion.character": "Carattere",
        "motion.stagger": "Entrata scaglionata delle schede",
        "motion.glow": "Bagliore della selezione",
        "motion.flight": "Volo verso la finestra scelta",
        "motion.n.none": "Nessuna animazione: risposta più rapida.",
        "motion.n.snappy": "Breve e netto; ideale con pressioni rapide di Tab.",
        "motion.n.spring": "Molla con leggero rimbalzo. Predefinito.",
        "motion.n.smooth": "Attenuazione morbida, senza rimbalzo.",
        "motion.n.dramatic": "Durate lunghe, rimbalzo marcato.",

        "glass.frosted": "Entrata in vetro smerigliato",
        "glass.frosted.note": "Le schede partono sfocate e si definiscono, come un vetro smerigliato che scorre via.",
        "glass.strength": "Intensità della smerigliatura",
        "glass.cards": "Schede in vetro",
        "glass.depth": "Profondità di campo",
        "glass.depth.note": "Le schede più lontane dalla selezione perdono leggermente la messa a fuoco.",
        "glass.sheen": "Riflesso speculare",
        "glass.reflection": "Riflesso",
        "glass.tint": "Tinta dalla finestra",
        "glass.tint.note": "Il bordo e il bagliore della scheda selezionata usano il colore dominante di quella finestra.",

        "transition.scrim": "Scurisci lo sfondo",
        "transition.dim": "Scurimento",
        "transition.blur": "Sfoca lo sfondo",
        "transition.scrim.note": "La scrivania reale viene sfocata; non viene acquisita alcuna schermata.",
        "transition.pulse": "Impulso di arrivo",
        "transition.pulse.note": "L'anteprima atterra sulla finestra di destinazione, poi una cornice luminosa pulsa una volta attorno.",
        "transition.collapse": "Contrai il pannello sulla selezione",
        "transition.parallax": "Inclinazione parallasse col puntatore",
        "transition.parallax.note": "Il pannello si inclina leggermente verso il puntatore.",

        "common.preview": "Anteprima",
        "common.reset": "Ripristina valori",
        "common.quit": "Esci da Vitrin",
        "common.cancel": "Annulla",
        "common.done": "Fine",
        "quit.title": "Uscire da Vitrin?",
        "quit.body": "Il selettore si ferma e la scorciatoia non funzionerà più. Dovrai aprire Vitrin dal Finder per riavviarlo.",

        "switcher.all": "tutte le finestre",
        "switcher.sameApp": "stessa app",
        "switcher.count": "finestre",
        "hint.forward": "avanti",
        "hint.back": "indietro",
        "hint.sameApp": "stessa app",
        "hint.close": "chiudi",
        "hint.minimize": "riduci",
        "hint.settings": "impostazioni",
        "hint.cancel": "annulla",

        "about.subtitle": "Selettore a livello di finestra",
        "about.version": "Versione",
        "about.what": "Cosa fa",
        "about.what.body": "Seleziona finestre, non app. Più finestre della stessa app compaiono separatamente, ciascuna con la propria anteprima dal vivo.",
        "about.how": "Come funziona",
        "about.how.body": "La scorciatoia viene catturata con un CGEvent tap. Le finestre arrivano da CGWindowList, quelle ridotte dall'API di accessibilità. Le anteprime sono acquisite in parallelo con ScreenCaptureKit.",
        "about.perms": "Permessi necessari",
        "about.perms.body": "Accessibilità: per sentire la scorciatoia e portare le finestre in primo piano. Registrazione schermo: per titoli e anteprime.",
        "about.copy": "Copia versione",
        "about.author": "Progettazione e sviluppo",

        "layout.grid": "Griglia",
        "layout.filmstrip": "Pellicola",
        "layout.coverflow": "Coverflow",
        "layout.radial": "Ventaglio",
        "layout.book": "Libro",
        "layout.grid.n": "Tutto insieme; il più leggibile con molte finestre",
        "layout.filmstrip.n": "Una sola riga; la scheda scelta cresce al centro",
        "layout.coverflow.n": "Schede ruotate in 3D; quella scelta viene in primo piano",
        "layout.radial.n": "Le schede sono disposte lungo un arco",
        "layout.book.n": "Come sfogliare; le schede superate cadono a sinistra",

        "motion.none": "Disattivato",
        "motion.snappy": "Scattante",
        "motion.spring": "Elastico",
        "motion.smooth": "Morbido",
        "motion.dramatic": "Scenografico",

        "entrance.rise": "Salita",
        "entrance.fold": "Apertura",
        "entrance.flip": "Ribaltamento",
        "entrance.rise.n": "Le schede salgono leggermente dal basso e si definiscono.",
        "entrance.fold.n": "Come un telefono pieghevole che si apre; le schede si spianano dal bordo sinistro.",
        "entrance.flip.n": "Le schede arrivano ribaltandosi sul proprio asse.",

        "material.hud": "HUD",
        "material.dark": "Scuro",
        "material.ultraThin": "Vetro sottile",
        "material.sidebar": "Barra laterale",

        "alert.ax.title": "Permesso di accessibilità necessario",
        "alert.ax.body": "Vitrin ha bisogno del permesso di accessibilità per catturare la scorciatoia. Si attiva da solo una volta concesso; altrimenti esci dalla barra dei menu e riaprilo.",
        "alert.tap.title": "Impossibile ascoltare gli eventi da tastiera",
        "alert.tap.body": "Non è stato possibile creare il CGEvent tap. Se Vitrin è elencato in Accessibilità, rimuovi la voce con (–), esci dall'app, riaprila e concedi di nuovo il permesso.",
        "alert.openSettings": "Apri impostazioni",
        "alert.later": "Più tardi",
        "alert.close": "Chiudi"
    ]
}
