// Vitrin — macOS window-level switcher
// Copyright (C) 2026 Çağlar Ülküderner
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version. See <https://www.gnu.org/licenses/> for details.
//
// https://github.com/ulkuderner/vitrin

extension Strings {
    static let es: [String: String] = [
        "menu.settings": "Ajustes…",
        "menu.about": "Acerca de Vitrin",
        "menu.showNow": "Mostrar ventanas ahora",
        "menu.accessibility": "Ajustes de accesibilidad",
        "menu.screenRecording": "Ajustes de grabación de pantalla",
        "menu.retryTap": "Reintentar la escucha del teclado",
        "menu.quit": "Salir",
        "status.ax": "Accesibilidad",
        "status.sr": "Grabación de pantalla",
        "status.tap": "Escucha",

        "tab.general": "General",
        "tab.appearance": "Aspecto",
        "tab.motion": "Movimiento",
        "tab.glass": "Cristal",
        "tab.transition": "Transición",
        "tab.about": "Acerca de",

        "general.trigger": "Tecla de activación",
        "general.trigger.note": "Mantén esta tecla y pulsa Tab. En teclados con distribución de PC, la tecla Alt física suele enviar Command.",
        "general.language": "Idioma",
        "general.login": "Abrir al iniciar sesión",
        "general.login.approval": "macOS espera tu aprobación: abre Ajustes del Sistema › General › Ítems de inicio y activa Vitrin.",
        "general.login.note": "Vitrin se inicia en segundo plano al iniciar sesión; no se abre ninguna ventana.",
        "general.minimized": "Listar ventanas minimizadas",
        "general.titles": "Mostrar títulos de ventana",
        "general.footer": "Mostrar la barra de ayuda",
        "general.icon": "Mostrar icono en la barra de menús",
        "general.icon.note": "Con el icono oculto puedes llegar a los ajustes de tres formas: pulsar la coma con el selector abierto, volver a abrir Vitrin desde el Finder o ejecutar open -a Vitrin.",
        "general.hide.title": "¿Ocultar el icono de la barra de menús?",
        "general.hide.body": "Sin el icono, puedes llegar a los ajustes así:\n\n• Pulsa la coma ( , ) con el selector abierto\n• Vuelve a abrir Vitrin desde el Finder\n• Ejecuta: open -a Vitrin\n\nUsa el botón de la parte inferior de esta ventana para salir.",
        "general.hide.ok": "Ocultar",

        "appearance.layout": "Disposición",
        "appearance.entrance": "Entrada",
        "appearance.cellWidth": "Ancho de tarjeta",
        "appearance.thumbHeight": "Alto de la previsualización",
        "appearance.columns": "Columnas máx.",
        "appearance.rows": "Filas máx.",
        "appearance.material": "Fondo",
        "appearance.opacity": "Transparencia del panel",
        "appearance.shadow": "Sombra del panel",
        "appearance.corner": "Radio de esquina",
        "appearance.op.zero": "Totalmente transparente: las tarjetas flotan directamente sobre el escritorio.",
        "appearance.op.mid": "Semitransparente; las ventanas de detrás siguen siendo legibles.",
        "appearance.op.full": "Material completo: la opción más legible.",

        "motion.character": "Carácter",
        "motion.stagger": "Entrada escalonada de las tarjetas",
        "motion.glow": "Resplandor de selección",
        "motion.flight": "Vuelo hacia la ventana elegida",
        "motion.n.none": "Sin animaciones: la respuesta más rápida.",
        "motion.n.snappy": "Breve y seco; ideal al pulsar Tab rápido.",
        "motion.n.spring": "Muelle con un ligero rebote. Predeterminado.",
        "motion.n.smooth": "Suavizado sin rebote.",
        "motion.n.dramatic": "Duraciones largas, rebote marcado.",

        "glass.frosted": "Entrada de cristal esmerilado",
        "glass.frosted.note": "Las tarjetas empiezan desenfocadas y se aclaran, como un cristal esmerilado que se retira.",
        "glass.strength": "Intensidad del esmerilado",
        "glass.cards": "Tarjetas de cristal",
        "glass.depth": "Profundidad de campo",
        "glass.depth.note": "Las tarjetas más lejanas a la selección pierden un poco de enfoque.",
        "glass.sheen": "Destello especular",
        "glass.reflection": "Reflejo",
        "glass.tint": "Tinte de la ventana",
        "glass.tint.note": "El borde y el resplandor de la tarjeta seleccionada usan el color dominante de esa ventana.",

        "transition.scrim": "Oscurecer el fondo",
        "transition.dim": "Oscurecimiento",
        "transition.blur": "Desenfocar el fondo",
        "transition.scrim.note": "El escritorio real se desenfoca; no se toma ninguna captura.",
        "transition.pulse": "Pulso de llegada",
        "transition.pulse.note": "La miniatura aterriza sobre la ventana de destino y luego un marco luminoso late una vez a su alrededor.",
        "transition.collapse": "Contraer el panel hacia la selección",
        "transition.parallax": "Inclinación de paralaje con el puntero",
        "transition.parallax.note": "El panel se inclina levemente hacia el puntero.",

        "common.preview": "Previsualizar",
        "common.reset": "Restablecer valores",
        "common.quit": "Salir de Vitrin",
        "common.cancel": "Cancelar",
        "common.done": "Listo",
        "quit.title": "¿Salir de Vitrin?",
        "quit.body": "El selector se detiene y el atajo dejará de funcionar. Tendrás que abrir Vitrin desde el Finder para volver a iniciarlo.",

        "switcher.all": "todas las ventanas",
        "switcher.sameApp": "misma app",
        "switcher.count": "ventanas",
        "hint.forward": "avanzar",
        "hint.back": "atrás",
        "hint.sameApp": "misma app",
        "hint.close": "cerrar",
        "hint.minimize": "minimizar",
        "hint.settings": "ajustes",
        "hint.cancel": "cancelar",

        "about.subtitle": "Selector a nivel de ventana",
        "about.version": "Versión",
        "about.what": "Qué hace",
        "about.what.body": "Selecciona ventanas, no apps. Varias ventanas de una misma app aparecen por separado, cada una con su previsualización en vivo.",
        "about.how": "Cómo funciona",
        "about.how.body": "El atajo se captura con un CGEvent tap. Las ventanas provienen de CGWindowList y las minimizadas de la API de accesibilidad. Las previsualizaciones se capturan en paralelo con ScreenCaptureKit.",
        "about.perms": "Permisos necesarios",
        "about.perms.body": "Accesibilidad: para oír el atajo y traer ventanas al frente. Grabación de pantalla: para títulos y previsualizaciones.",
        "about.copy": "Copiar versión",
        "about.author": "Diseño y desarrollo",

        "layout.grid": "Cuadrícula",
        "layout.filmstrip": "Tira de película",
        "layout.coverflow": "Coverflow",
        "layout.radial": "Abanico",
        "layout.book": "Libro",
        "layout.grid.n": "Todo a la vez; lo más legible con muchas ventanas",
        "layout.filmstrip.n": "Una sola fila; la tarjeta elegida crece en el centro",
        "layout.coverflow.n": "Tarjetas giradas en 3D; la elegida pasa al frente",
        "layout.radial.n": "Las tarjetas se disponen sobre un arco",
        "layout.book.n": "Como pasar páginas; las tarjetas superadas caen a la izquierda",

        "motion.none": "Desactivado",
        "motion.snappy": "Ágil",
        "motion.spring": "Con muelle",
        "motion.smooth": "Suave",
        "motion.dramatic": "Espectacular",

        "entrance.rise": "Ascenso",
        "entrance.fold": "Despliegue",
        "entrance.flip": "Volteo",
        "entrance.rise.n": "Las tarjetas suben ligeramente y se enfocan.",
        "entrance.fold.n": "Como un teléfono plegable al abrirse; las tarjetas se despliegan desde su borde izquierdo.",
        "entrance.flip.n": "Las tarjetas llegan volteando sobre su propio eje.",

        "material.hud": "HUD",
        "material.dark": "Oscuro",
        "material.ultraThin": "Cristal fino",
        "material.sidebar": "Barra lateral",

        "alert.ax.title": "Se requiere permiso de accesibilidad",
        "alert.ax.body": "Vitrin necesita permiso de accesibilidad para capturar el atajo. Se activa solo en cuanto lo concedas; si no, sal desde la barra de menús y vuelve a abrirlo.",
        "alert.tap.title": "No se pudieron escuchar los eventos de teclado",
        "alert.tap.body": "No se pudo crear el CGEvent tap. Si Vitrin aparece en Accesibilidad, elimina la entrada con (–), sal de la app, vuelve a abrirla y concede el permiso de nuevo.",
        "alert.openSettings": "Abrir ajustes",
        "alert.later": "Más tarde",
        "alert.close": "Cerrar"
    ]
}