extension Strings {
    static let fr: [String: String] = [
        "menu.settings": "Réglages…",
        "menu.about": "À propos de Vitrin",
        "menu.showNow": "Afficher les fenêtres",
        "menu.accessibility": "Réglages d'accessibilité",
        "menu.screenRecording": "Réglages d'enregistrement de l'écran",
        "menu.retryTap": "Réessayer l'écoute du clavier",
        "menu.quit": "Quitter",
        "status.ax": "Accessibilité",
        "status.sr": "Enregistrement d'écran",
        "status.tap": "Écoute",

        "tab.general": "Général",
        "tab.appearance": "Apparence",
        "tab.motion": "Mouvement",
        "tab.glass": "Verre",
        "tab.transition": "Transition",
        "tab.about": "À propos",

        "general.trigger": "Touche de déclenchement",
        "general.trigger.note": "Maintenez cette touche et appuyez sur Tab. Sur les claviers de type PC, la touche Alt physique envoie souvent Command.",
        "general.language": "Langue",
        "general.login": "Lancer à l'ouverture de session",
        "general.login.approval": "macOS attend votre confirmation : ouvrez Réglages Système › Général › Ouverture et activez Vitrin.",
        "general.login.note": "Vitrin démarre discrètement en arrière-plan à l'ouverture de session ; aucune fenêtre ne s'ouvre.",
        "general.minimized": "Lister les fenêtres réduites",
        "general.titles": "Afficher les titres des fenêtres",
        "general.footer": "Afficher la barre d'aide",
        "general.icon": "Afficher l'icône dans la barre des menus",
        "general.icon.note": "Sans l'icône, trois moyens d'accéder aux réglages : appuyer sur la virgule pendant que le sélecteur est ouvert, rouvrir Vitrin depuis le Finder, ou lancer open -a Vitrin.",
        "general.hide.title": "Masquer l'icône de la barre des menus ?",
        "general.hide.body": "Une fois l'icône masquée, accédez aux réglages ainsi :\n\n• Appuyez sur la virgule ( , ) pendant que le sélecteur est ouvert\n• Rouvrez Vitrin depuis le Finder\n• Lancez : open -a Vitrin\n\nUtilisez le bouton en bas de cette fenêtre pour quitter.",
        "general.hide.ok": "Masquer",

        "appearance.layout": "Disposition",
        "appearance.entrance": "Entrée",
        "appearance.cellWidth": "Largeur des cartes",
        "appearance.thumbHeight": "Hauteur de l'aperçu",
        "appearance.columns": "Colonnes max.",
        "appearance.rows": "Rangées max.",
        "appearance.material": "Arrière-plan",
        "appearance.opacity": "Transparence du panneau",
        "appearance.shadow": "Ombre du panneau",
        "appearance.corner": "Rayon des coins",
        "appearance.op.zero": "Entièrement transparent — les cartes flottent directement au-dessus du bureau.",
        "appearance.op.mid": "Semi-transparent ; les fenêtres derrière restent lisibles.",
        "appearance.op.full": "Matériau complet — le plus lisible.",

        "motion.character": "Caractère",
        "motion.stagger": "Entrée échelonnée des cartes",
        "motion.glow": "Halo de sélection",
        "motion.flight": "Vol vers la fenêtre choisie",
        "motion.n.none": "Aucune animation — réaction la plus rapide.",
        "motion.n.snappy": "Bref et net ; idéal pour les appuis rapides sur Tab.",
        "motion.n.spring": "Ressort avec un léger dépassement. Par défaut.",
        "motion.n.smooth": "Lissage doux, sans dépassement.",
        "motion.n.dramatic": "Durées longues, dépassement marqué.",

        "glass.frosted": "Entrée en verre dépoli",
        "glass.frosted.note": "Les cartes commencent floues puis se précisent — comme un verre dépoli qui s'écarte.",
        "glass.strength": "Intensité du givre",
        "glass.cards": "Cartes en verre",
        "glass.depth": "Profondeur de champ",
        "glass.depth.note": "Les cartes éloignées de la sélection perdent légèrement la mise au point.",
        "glass.sheen": "Reflet spéculaire",
        "glass.reflection": "Reflet",
        "glass.tint": "Teinte issue de la fenêtre",
        "glass.tint.note": "La bordure et le halo de la carte sélectionnée reprennent la couleur dominante de la fenêtre.",

        "transition.scrim": "Assombrir l'arrière-plan",
        "transition.dim": "Assombrissement",
        "transition.blur": "Flouter l'arrière-plan",
        "transition.scrim.note": "Le bureau réel est flouté ; aucune capture d'écran n'est réalisée.",
        "transition.pulse": "Pulsation d'arrivée",
        "transition.pulse.note": "L'aperçu se pose sur la fenêtre cible, puis un cadre lumineux pulse une fois autour d'elle.",
        "transition.collapse": "Replier le panneau vers la sélection",
        "transition.parallax": "Inclinaison parallaxe au pointeur",
        "transition.parallax.note": "Le panneau s'incline légèrement vers le pointeur.",

        "common.preview": "Aperçu",
        "common.reset": "Valeurs par défaut",
        "common.quit": "Quitter Vitrin",
        "common.cancel": "Annuler",
        "common.done": "Terminé",
        "quit.title": "Quitter Vitrin ?",
        "quit.body": "Le sélecteur s'arrête et le raccourci ne fonctionnera plus. Vous devrez ouvrir Vitrin depuis le Finder pour le relancer.",

        "switcher.all": "toutes les fenêtres",
        "switcher.sameApp": "même app",
        "switcher.count": "fenêtres",
        "hint.forward": "suivant",
        "hint.back": "précédent",
        "hint.sameApp": "même app",
        "hint.close": "fermer",
        "hint.minimize": "réduire",
        "hint.settings": "réglages",
        "hint.cancel": "annuler",

        "about.subtitle": "Sélecteur au niveau des fenêtres",
        "about.version": "Version",
        "about.what": "Ce qu'il fait",
        "about.what.body": "Il sélectionne des fenêtres, pas des apps. Plusieurs fenêtres d'une même app sont listées séparément, chacune avec son aperçu en direct.",
        "about.how": "Fonctionnement",
        "about.how.body": "Le raccourci est capté par un CGEvent tap. Les fenêtres proviennent de CGWindowList, les réduites de l'API d'accessibilité. Les aperçus sont capturés en parallèle avec ScreenCaptureKit.",
        "about.perms": "Autorisations requises",
        "about.perms.body": "Accessibilité : pour entendre le raccourci et mettre les fenêtres au premier plan. Enregistrement de l'écran : pour les titres et les aperçus.",
        "about.copy": "Copier la version",
        "about.author": "Conception et développement",

        "layout.grid": "Grille",
        "layout.filmstrip": "Pellicule",
        "layout.coverflow": "Coverflow",
        "layout.radial": "Éventail",
        "layout.book": "Livre",
        "layout.grid.n": "Tout à la fois ; le plus lisible avec beaucoup de fenêtres",
        "layout.filmstrip.n": "Une seule rangée ; la carte choisie grandit au centre",
        "layout.coverflow.n": "Cartes pivotées en 3D ; la carte choisie passe devant",
        "layout.radial.n": "Les cartes sont disposées sur un arc",
        "layout.book.n": "Comme tourner des pages ; les cartes passées tombent à gauche",

        "motion.none": "Désactivé",
        "motion.snappy": "Vif",
        "motion.spring": "Ressort",
        "motion.smooth": "Doux",
        "motion.dramatic": "Spectaculaire",

        "entrance.rise": "Montée",
        "entrance.fold": "Dépliage",
        "entrance.flip": "Bascule",
        "entrance.rise.n": "Les cartes montent légèrement et se précisent.",
        "entrance.fold.n": "Comme un téléphone pliable qui s'ouvre ; les cartes se déplient depuis leur bord gauche.",
        "entrance.flip.n": "Les cartes arrivent en basculant sur leur propre axe.",

        "material.hud": "HUD",
        "material.dark": "Sombre",
        "material.ultraThin": "Verre fin",
        "material.sidebar": "Barre latérale",

        "alert.ax.title": "Autorisation d'accessibilité requise",
        "alert.ax.body": "Vitrin a besoin de l'autorisation d'accessibilité pour capter le raccourci. Il s'active de lui-même une fois accordée ; sinon, quittez depuis la barre des menus et rouvrez.",
        "alert.tap.title": "Impossible d'écouter les événements clavier",
        "alert.tap.body": "Le CGEvent tap n'a pas pu être créé. Si Vitrin figure sous Accessibilité, supprimez l'entrée avec (–), quittez l'app, rouvrez-la et accordez à nouveau l'autorisation.",
        "alert.openSettings": "Ouvrir les réglages",
        "alert.later": "Plus tard",
        "alert.close": "Fermer"
    ]
}
