extension Strings {
    static let ru: [String: String] = [
        "menu.settings": "Настройки…",
        "menu.about": "О программе Vitrin",
        "menu.showNow": "Показать окна сейчас",
        "menu.accessibility": "Настройки универсального доступа",
        "menu.screenRecording": "Настройки записи экрана",
        "menu.retryTap": "Повторить перехват клавиатуры",
        "menu.quit": "Завершить",
        "status.ax": "Универсальный доступ",
        "status.sr": "Запись экрана",
        "status.tap": "Перехват",

        "tab.general": "Основные",
        "tab.appearance": "Внешний вид",
        "tab.motion": "Движение",
        "tab.glass": "Стекло",
        "tab.transition": "Переход",
        "tab.about": "О программе",

        "general.trigger": "Клавиша вызова",
        "general.trigger.note": "Удерживайте эту клавишу и нажимайте Tab. На клавиатурах с раскладкой ПК физическая клавиша Alt обычно посылает Command.",
        "general.language": "Язык",
        "general.login": "Запускать при входе",
        "general.login.approval": "macOS ждёт вашего подтверждения: откройте «Системные настройки › Основные › Объекты входа» и включите Vitrin.",
        "general.login.note": "Vitrin запускается при входе в систему незаметно, в фоне; ни одно окно не открывается.",
        "general.minimized": "Показывать свёрнутые окна",
        "general.titles": "Показывать заголовки окон",
        "general.footer": "Показывать строку подсказок",
        "general.icon": "Показывать значок в строке меню",
        "general.icon.note": "Если значок скрыт, до настроек можно добраться тремя способами: нажать запятую при открытом переключателе, открыть Vitrin заново из Finder или выполнить open -a Vitrin.",
        "general.hide.title": "Скрыть значок в строке меню?",
        "general.hide.body": "Без значка настройки открываются так:\n\n• Нажмите запятую ( , ) при открытом переключателе\n• Откройте Vitrin заново из Finder\n• Выполните: open -a Vitrin\n\nДля выхода используйте кнопку внизу этого окна.",
        "general.hide.ok": "Скрыть",

        "appearance.layout": "Раскладка",
        "appearance.entrance": "Появление",
        "appearance.cellWidth": "Ширина карточки",
        "appearance.thumbHeight": "Высота миниатюры",
        "appearance.columns": "Макс. столбцов",
        "appearance.rows": "Макс. строк",
        "appearance.material": "Фон",
        "appearance.opacity": "Прозрачность панели",
        "appearance.shadow": "Тень панели",
        "appearance.corner": "Радиус скругления",
        "appearance.op.zero": "Полностью прозрачно — карточки парят прямо над рабочим столом.",
        "appearance.op.mid": "Полупрозрачно; окна позади остаются читаемыми.",
        "appearance.op.full": "Полный материал — самый читаемый вариант.",

        "motion.character": "Характер",
        "motion.stagger": "Карточки появляются по очереди",
        "motion.glow": "Свечение выбора",
        "motion.flight": "Полёт к выбранному окну",
        "motion.n.none": "Анимация выключена — самый быстрый отклик.",
        "motion.n.snappy": "Коротко и чётко; лучше всего при быстрых нажатиях Tab.",
        "motion.n.spring": "Пружина с лёгким перелётом. По умолчанию.",
        "motion.n.smooth": "Мягкое сглаживание, без перелёта.",
        "motion.n.dramatic": "Долгие длительности, заметный перелёт.",

        "glass.frosted": "Появление сквозь матовое стекло",
        "glass.frosted.note": "Карточки начинают размытыми и становятся резкими — будто матовое стекло отъезжает в сторону.",
        "glass.strength": "Сила матовости",
        "glass.cards": "Стеклянные карточки",
        "glass.depth": "Глубина резкости",
        "glass.depth.note": "Карточки дальше от выбранной слегка теряют резкость.",
        "glass.sheen": "Блик",
        "glass.reflection": "Отражение",
        "glass.tint": "Цвет из окна",
        "glass.tint.note": "Рамка и свечение выбранной карточки берут преобладающий цвет этого окна.",

        "transition.scrim": "Затемнять фон",
        "transition.dim": "Затемнение",
        "transition.blur": "Размывать фон",
        "transition.scrim.note": "Размывается настоящий рабочий стол; снимок экрана не делается.",
        "transition.pulse": "Импульс прибытия",
        "transition.pulse.note": "Миниатюра приземляется на целевое окно, затем вокруг него один раз пульсирует светящаяся рамка.",
        "transition.collapse": "Сворачивать панель к выбранной карточке",
        "transition.parallax": "Наклон-параллакс за указателем",
        "transition.parallax.note": "Панель слегка наклоняется в сторону указателя.",

        "common.preview": "Просмотр",
        "common.reset": "Сбросить настройки",
        "common.quit": "Завершить Vitrin",
        "common.cancel": "Отменить",
        "common.done": "Готово",
        "quit.title": "Завершить Vitrin?",
        "quit.body": "Переключатель остановится, и сочетание клавиш перестанет работать. Чтобы запустить снова, откройте Vitrin из Finder.",

        "switcher.all": "все окна",
        "switcher.sameApp": "та же программа",
        "switcher.count": "окон",
        "hint.forward": "вперёд",
        "hint.back": "назад",
        "hint.sameApp": "та же программа",
        "hint.close": "закрыть",
        "hint.minimize": "свернуть",
        "hint.settings": "настройки",
        "hint.cancel": "отмена",

        "about.subtitle": "Переключатель на уровне окон",
        "about.version": "Версия",
        "about.what": "Что делает",
        "about.what.body": "Выбирает окна, а не программы. Несколько окон одной программы перечислены отдельно, каждое со своей живой миниатюрой.",
        "about.how": "Как работает",
        "about.how.body": "Сочетание перехватывается через CGEvent tap. Окна берутся из CGWindowList, свёрнутые — из Accessibility API. Миниатюры снимаются параллельно через ScreenCaptureKit.",
        "about.perms": "Необходимые разрешения",
        "about.perms.body": "Универсальный доступ: чтобы услышать сочетание и вывести окно вперёд. Запись экрана: для заголовков и миниатюр.",
        "about.copy": "Скопировать версию",
        "about.author": "Дизайн и разработка",

        "layout.grid": "Сетка",
        "layout.filmstrip": "Плёнка",
        "layout.coverflow": "Coverflow",
        "layout.radial": "Веер",
        "layout.book": "Книга",
        "layout.grid.n": "Всё сразу; самый читаемый вариант при многих окнах",
        "layout.filmstrip.n": "Один ряд; выбранная карточка растёт в центре",
        "layout.coverflow.n": "Карточки повёрнуты в 3D; выбранная выходит вперёд",
        "layout.radial.n": "Карточки расположены по дуге",
        "layout.book.n": "Как перелистывание; пройденные карточки ложатся налево",

        "motion.none": "Выключено",
        "motion.snappy": "Резко",
        "motion.spring": "Пружинисто",
        "motion.smooth": "Плавно",
        "motion.dramatic": "Выразительно",

        "entrance.rise": "Подъём",
        "entrance.fold": "Раскрытие",
        "entrance.flip": "Переворот",
        "entrance.rise.n": "Карточки слегка поднимаются снизу и становятся резкими.",
        "entrance.fold.n": "Как раскрывающийся складной телефон; карточки распрямляются от левого края.",
        "entrance.flip.n": "Карточки появляются, переворачиваясь вокруг своей оси.",

        "material.hud": "HUD",
        "material.dark": "Тёмный",
        "material.ultraThin": "Тонкое стекло",
        "material.sidebar": "Боковое меню",

        "alert.ax.title": "Требуется разрешение универсального доступа",
        "alert.ax.body": "Vitrin нужно разрешение универсального доступа, чтобы перехватывать сочетание клавиш. После выдачи он включится сам; если нет — завершите его из строки меню и откройте заново.",
        "alert.tap.title": "Не удалось перехватить события клавиатуры",
        "alert.tap.body": "Не удалось создать CGEvent tap. Если Vitrin есть в списке «Универсальный доступ», удалите запись кнопкой (–), завершите программу, откройте её заново и выдайте разрешение снова.",
        "alert.openSettings": "Открыть настройки",
        "alert.later": "Позже",
        "alert.close": "Закрыть"
    ]
}
