// Vitrin — macOS window-level switcher
// Copyright (C) 2026 Çağlar Ülküderner
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version. See <https://www.gnu.org/licenses/> for details.
//
// https://github.com/ulkuderner/vitrin

extension Strings {
    static let nl: [String: String] = [
        "menu.settings": "Instellingen…",
        "menu.about": "Over Vitrin",
        "menu.showNow": "Vensters nu tonen",
        "menu.accessibility": "Toegankelijkheidsinstellingen",
        "menu.screenRecording": "Instellingen voor schermopname",
        "menu.retryTap": "Toetsenbord opnieuw proberen te lezen",
        "menu.quit": "Stop",
        "status.ax": "Toegankelijkheid",
        "status.sr": "Schermopname",
        "status.tap": "Luisteren",

        "tab.general": "Algemeen",
        "tab.appearance": "Weergave",
        "tab.motion": "Beweging",
        "tab.glass": "Glas",
        "tab.transition": "Overgang",
        "tab.about": "Over",

        "general.trigger": "Activeringstoets",
        "general.trigger.note": "Houd deze toets ingedrukt en druk op Tab. Op toetsenborden met pc-indeling stuurt de fysieke Alt-toets meestal Command.",
        "general.language": "Taal",
        "general.login": "Starten bij inloggen",
        "general.login.approval": "macOS wacht op je goedkeuring: open Systeeminstellingen › Algemeen › Inlogonderdelen en schakel Vitrin in.",
        "general.login.note": "Vitrin start bij het inloggen stil op de achtergrond; er wordt geen venster geopend.",
        "general.minimized": "Geminimaliseerde vensters tonen",
        "general.titles": "Venstertitels tonen",
        "general.footer": "Hintbalk tonen",
        "general.icon": "Menubalksymbool tonen",
        "general.icon.note": "Met verborgen symbool bereik je de instellingen op drie manieren: druk op de komma terwijl de kiezer open is, open Vitrin opnieuw via de Finder, of voer open -a Vitrin uit.",
        "general.hide.title": "Menubalksymbool verbergen?",
        "general.hide.body": "Zonder symbool bereik je de instellingen zo:\n\n• Druk op de komma ( , ) terwijl de kiezer open is\n• Open Vitrin opnieuw via de Finder\n• Voer uit: open -a Vitrin\n\nGebruik de knop onderaan dit venster om te stoppen.",
        "general.hide.ok": "Verberg",

        "appearance.layout": "Indeling",
        "appearance.entrance": "Verschijning",
        "appearance.cellWidth": "Kaartbreedte",
        "appearance.thumbHeight": "Hoogte van voorvertoning",
        "appearance.columns": "Max. kolommen",
        "appearance.rows": "Max. rijen",
        "appearance.material": "Achtergrond",
        "appearance.opacity": "Transparantie van paneel",
        "appearance.shadow": "Paneelschaduw",
        "appearance.corner": "Hoekradius",
        "appearance.op.zero": "Volledig transparant: de kaarten zweven direct boven het bureaublad.",
        "appearance.op.mid": "Halftransparant; vensters erachter blijven leesbaar.",
        "appearance.op.full": "Vol materiaal: het best leesbaar.",

        "motion.character": "Karakter",
        "motion.stagger": "Kaarten na elkaar laten verschijnen",
        "motion.glow": "Gloed bij selectie",
        "motion.flight": "Vlucht naar het gekozen venster",
        "motion.n.none": "Alle animatie uit — de snelste reactie.",
        "motion.n.snappy": "Kort en strak; ideaal bij snel drukken op Tab.",
        "motion.n.spring": "Veer met een lichte doorschot. Standaard.",
        "motion.n.smooth": "Zachte easing, geen doorschot.",
        "motion.n.dramatic": "Langere duur, duidelijke doorschot.",

        "glass.frosted": "Matglas-verschijning",
        "glass.frosted.note": "Kaarten beginnen wazig en worden scherp — alsof matglas wegschuift.",
        "glass.strength": "Matheid",
        "glass.cards": "Kaarten van glas",
        "glass.depth": "Scherptediepte",
        "glass.depth.note": "Kaarten verder van de selectie verliezen iets aan scherpte.",
        "glass.sheen": "Lichtstreep",
        "glass.reflection": "Spiegeling",
        "glass.tint": "Kleur uit het venster",
        "glass.tint.note": "De rand en gloed van de gekozen kaart nemen de dominante kleur van dat venster over.",

        "transition.scrim": "Achtergrond dimmen",
        "transition.dim": "Dimming",
        "transition.blur": "Achtergrond vervagen",
        "transition.scrim.note": "Het echte bureaublad wordt vervaagd; er wordt geen schermafbeelding gemaakt.",
        "transition.pulse": "Aankomstpuls",
        "transition.pulse.note": "De miniatuur landt op het doelvenster, waarna er één keer een lichtgevende rand omheen pulseert.",
        "transition.collapse": "Paneel naar de selectie laten krimpen",
        "transition.parallax": "Parallax-kanteling met de aanwijzer",
        "transition.parallax.note": "Het paneel kantelt licht richting de aanwijzer.",

        "common.preview": "Voorvertoning",
        "common.reset": "Standaardwaarden",
        "common.quit": "Vitrin stoppen",
        "common.cancel": "Annuleer",
        "common.done": "Gereed",
        "quit.title": "Vitrin stoppen?",
        "quit.body": "De kiezer stopt en de sneltoets werkt niet meer. Je moet Vitrin via de Finder openen om het opnieuw te starten.",

        "switcher.all": "alle vensters",
        "switcher.sameApp": "zelfde app",
        "switcher.count": "vensters",
        "hint.forward": "vooruit",
        "hint.back": "terug",
        "hint.sameApp": "zelfde app",
        "hint.close": "sluiten",
        "hint.minimize": "minimaliseren",
        "hint.settings": "instellingen",
        "hint.cancel": "annuleren",

        "about.subtitle": "Kiezer op vensterniveau",
        "about.version": "Versie",
        "about.what": "Wat het doet",
        "about.what.body": "Het kiest vensters, geen apps. Meerdere vensters van één app staan apart in de lijst, elk met een eigen live voorvertoning.",
        "about.how": "Hoe het werkt",
        "about.how.body": "De sneltoets wordt met een CGEvent tap opgevangen. Vensters komen uit CGWindowList, geminimaliseerde uit de Accessibility-API. Voorvertoningen worden parallel gemaakt met ScreenCaptureKit.",
        "about.perms": "Vereiste toegang",
        "about.perms.body": "Toegankelijkheid: om de sneltoets te horen en vensters naar voren te halen. Schermopname: voor titels en voorvertoningen.",
        "about.license": "Licentie",
        "about.license.body": "GNU General Public License v3.0. Vrij te gebruiken, bestuderen, wijzigen en delen; afgeleide werken moeten onder dezelfde licentie open blijven.",
        "about.source": "Broncode",
        "about.copy": "Versie kopiëren",
        "about.author": "Ontwerp en ontwikkeling",

        "layout.grid": "Raster",
        "layout.filmstrip": "Filmstrook",
        "layout.coverflow": "Coverflow",
        "layout.radial": "Waaier",
        "layout.book": "Boek",
        "layout.grid.n": "Alles tegelijk; het best leesbaar bij veel vensters",
        "layout.filmstrip.n": "Eén rij; de gekozen kaart groeit in het midden",
        "layout.coverflow.n": "In 3D gedraaide kaarten; de gekozen komt naar voren",
        "layout.radial.n": "De kaarten liggen op een boog",
        "layout.book.n": "Als bladeren; gepasseerde kaarten vallen naar links",

        "motion.none": "Uit",
        "motion.snappy": "Kordaat",
        "motion.spring": "Verend",
        "motion.smooth": "Zacht",
        "motion.dramatic": "Uitbundig",

        "entrance.rise": "Opkomen",
        "entrance.fold": "Openvouwen",
        "entrance.flip": "Omklappen",
        "entrance.rise.n": "De kaarten komen licht van onderen op en worden scherp.",
        "entrance.fold.n": "Als een opvouwbare telefoon die opengaat; de kaarten vouwen open vanaf hun linkerrand.",
        "entrance.flip.n": "De kaarten komen binnen door om hun eigen as te klappen.",

        "material.hud": "HUD",
        "material.dark": "Donker",
        "material.ultraThin": "Dun glas",
        "material.sidebar": "Navigatiekolom",

        "alert.ax.title": "Toegang tot toegankelijkheid vereist",
        "alert.ax.body": "Vitrin heeft toegankelijkheidstoegang nodig om de sneltoets op te vangen. Zodra je die verleent, wordt het vanzelf actief; zo niet, stop via de menubalk en open opnieuw.",
        "alert.tap.title": "Kon toetsenbordgebeurtenissen niet lezen",
        "alert.tap.body": "De CGEvent tap kon niet worden aangemaakt. Staat Vitrin onder Toegankelijkheid, verwijder de vermelding met (–), stop de app, open opnieuw en verleen de toegang nog eens.",
        "alert.openSettings": "Instellingen openen",
        "alert.later": "Later",
        "alert.close": "Sluit"
    ]
}