// Vitrin — macOS window-level switcher
// Copyright (C) 2026 Çağlar Ülküderner
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version. See <https://www.gnu.org/licenses/> for details.
//
// https://github.com/ulkuderner/vitrin

extension Strings {
    static let ja: [String: String] = [
        "menu.settings": "設定…",
        "menu.about": "Vitrin について",
        "menu.showNow": "ウインドウを今すぐ表示",
        "menu.accessibility": "アクセシビリティ設定",
        "menu.screenRecording": "画面収録の設定",
        "menu.retryTap": "キーボード監視を再試行",
        "menu.quit": "終了",
        "status.ax": "アクセシビリティ",
        "status.sr": "画面収録",
        "status.tap": "監視",

        "tab.general": "一般",
        "tab.appearance": "外観",
        "tab.motion": "モーション",
        "tab.glass": "ガラス",
        "tab.transition": "トランジション",
        "tab.about": "情報",

        "general.trigger": "トリガーキー",
        "general.trigger.note": "このキーを押しながら Tab を押します。PC 配列のキーボードでは、物理的な Alt キーが Command を送ることがよくあります。",
        "general.language": "言語",
        "general.login": "ログイン時に起動",
        "general.login.approval": "macOS が承認を待っています。「システム設定 › 一般 › ログイン項目」で Vitrin を有効にしてください。",
        "general.login.note": "ログイン時に Vitrin がバックグラウンドで静かに起動します。ウインドウは開きません。",
        "general.minimized": "しまってあるウインドウも一覧に含める",
        "general.titles": "ウインドウのタイトルを表示",
        "general.footer": "ヒントバーを表示",
        "general.icon": "メニューバーアイコンを表示",
        "general.icon.note": "アイコンを隠しても、設定へは 3 通りで戻れます。切り替え画面を開いた状態でカンマを押す、Finder から Vitrin を開き直す、または open -a Vitrin を実行する。",
        "general.hide.title": "メニューバーアイコンを隠しますか？",
        "general.hide.body": "アイコンを隠したあとは、次の方法で設定に戻れます:\n\n• 切り替え画面を開いた状態でカンマ ( , ) を押す\n• Finder から Vitrin を開き直す\n• ターミナルで: open -a Vitrin\n\n終了するには、このウインドウ下部のボタンを使います。",
        "general.hide.ok": "隠す",

        "appearance.layout": "並べ方",
        "appearance.entrance": "登場",
        "appearance.cellWidth": "カードの幅",
        "appearance.thumbHeight": "プレビューの高さ",
        "appearance.columns": "最大列数",
        "appearance.rows": "最大行数",
        "appearance.material": "背景",
        "appearance.opacity": "パネルの透明度",
        "appearance.shadow": "パネルの影",
        "appearance.corner": "角の丸み",
        "appearance.op.zero": "完全に透明 — カードがデスクトップの上に直接浮かびます。",
        "appearance.op.mid": "半透明。背後のウインドウも判別できます。",
        "appearance.op.full": "素材を全面に。もっとも読みやすい設定です。",

        "motion.character": "性格",
        "motion.stagger": "カードを順番に表示",
        "motion.glow": "選択時のグロー",
        "motion.flight": "選んだウインドウへ飛ばす",
        "motion.n.none": "アニメーションなし — 反応が最速です。",
        "motion.n.snappy": "短く歯切れよく。Tab を速く連打するときに最適です。",
        "motion.n.spring": "わずかに行きすぎるスプリング。標準です。",
        "motion.n.smooth": "なめらかなイージング。行きすぎはありません。",
        "motion.n.dramatic": "長めの時間と、はっきりした行きすぎ。",

        "glass.frosted": "すりガラスからの登場",
        "glass.frosted.note": "カードはぼやけた状態から鮮明になります。すりガラスが横に滑って外れるような感じです。",
        "glass.strength": "すりガラスの強さ",
        "glass.cards": "ガラス素材のカード",
        "glass.depth": "被写界深度",
        "glass.depth.note": "選択中のカードから離れるほど、わずかにピントが外れます。",
        "glass.sheen": "光沢の走り",
        "glass.reflection": "映り込み",
        "glass.tint": "ウインドウから色を取る",
        "glass.tint.note": "選択中のカードの枠とグローに、そのウインドウの主要な色を使います。",

        "transition.scrim": "背景を暗くする",
        "transition.dim": "暗さ",
        "transition.blur": "背景をぼかす",
        "transition.scrim.note": "実際のデスクトップがぼけます。スクリーンショットは撮りません。",
        "transition.pulse": "到着時のパルス",
        "transition.pulse.note": "サムネールが目的のウインドウに着地し、その周囲で光る枠が一度だけ脈打ちます。",
        "transition.collapse": "パネルを選択したカードへ畳む",
        "transition.parallax": "ポインタに合わせた視差の傾き",
        "transition.parallax.note": "パネルがポインタの方向へわずかに傾きます。",

        "common.preview": "プレビュー",
        "common.reset": "デフォルトに戻す",
        "common.quit": "Vitrin を終了",
        "common.cancel": "キャンセル",
        "common.done": "完了",
        "quit.title": "Vitrin を終了しますか？",
        "quit.body": "切り替え機能が停止し、ショートカットは効かなくなります。再開するには Finder から Vitrin を開いてください。",

        "switcher.all": "すべてのウインドウ",
        "switcher.sameApp": "同じApp",
        "switcher.count": "ウインドウ",
        "hint.forward": "次へ",
        "hint.back": "前へ",
        "hint.sameApp": "同じApp",
        "hint.close": "閉じる",
        "hint.minimize": "しまう",
        "hint.settings": "設定",
        "hint.cancel": "キャンセル",

        "about.subtitle": "ウインドウ単位の切り替えツール",
        "about.version": "バージョン",
        "about.what": "できること",
        "about.what.body": "App ではなくウインドウを選びます。同じ App の複数のウインドウはそれぞれ別に並び、どれにも実際のプレビューが付きます。",
        "about.how": "仕組み",
        "about.how.body": "ショートカットは CGEvent tap で捕まえます。ウインドウ一覧は CGWindowList から、しまってあるものはアクセシビリティ API から取得します。プレビューは ScreenCaptureKit で並行して取得します。",
        "about.perms": "必要な許可",
        "about.perms.body": "アクセシビリティ: ショートカットを受け取り、ウインドウを前面に出すため。画面収録: タイトルとプレビューのため。",
        "about.license": "ライセンス",
        "about.license.body": "GNU 一般公衆利用許諾書 v3.0。自由に使用・調査・改変・共有できます。派生物も同じライセンスで公開する必要があります。",
        "about.source": "ソースコード",
        "about.copy": "バージョンをコピー",
        "about.author": "デザインと開発",

        "layout.grid": "グリッド",
        "layout.filmstrip": "フィルムストリップ",
        "layout.coverflow": "カバーフロー",
        "layout.radial": "扇",
        "layout.book": "ブック",
        "layout.grid.n": "すべてを一度に。ウインドウが多いときにいちばん読みやすい並べ方です",
        "layout.filmstrip.n": "一列に並び、選んだカードが中央で大きくなります",
        "layout.coverflow.n": "3D で回転したカード。選んだものが手前に出ます",
        "layout.radial.n": "カードが弧を描いて並びます",
        "layout.book.n": "ページをめくるように。通り過ぎたカードは左側へ倒れます",

        "motion.none": "オフ",
        "motion.snappy": "きびきび",
        "motion.spring": "スプリング",
        "motion.smooth": "なめらか",
        "motion.dramatic": "大きめ",

        "entrance.rise": "せり上がる",
        "entrance.fold": "開く",
        "entrance.flip": "めくる",
        "entrance.rise.n": "カードが下からわずかにせり上がり、鮮明になります。",
        "entrance.fold.n": "折りたたみ式の電話が開くように、カードが左端から平らに開きます。",
        "entrance.flip.n": "カードが自身の軸で回転しながら現れます。",

        "material.hud": "HUD",
        "material.dark": "ダーク",
        "material.ultraThin": "薄いガラス",
        "material.sidebar": "サイドバー",

        "alert.ax.title": "アクセシビリティの許可が必要です",
        "alert.ax.body": "ショートカットを受け取るために、Vitrin はアクセシビリティの許可を必要とします。許可すると自動的に有効になります。ならない場合はメニューバーから終了し、開き直してください。",
        "alert.tap.title": "キーボードイベントを監視できませんでした",
        "alert.tap.body": "CGEvent tap を作成できませんでした。アクセシビリティの一覧に Vitrin がある場合は (–) で項目を削除し、App を終了して開き直し、もう一度許可してください。",
        "alert.openSettings": "設定を開く",
        "alert.later": "あとで",
        "alert.close": "閉じる"
    ]
}