// Vitrin — macOS window-level switcher
// Copyright (C) 2026 Çağlar Ülküderner
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version. See <https://www.gnu.org/licenses/> for details.
//
// https://github.com/ulkuderner/vitrin

extension Strings {
    static let en: [String: String] = [
        "menu.settings": "Settings…",
        "menu.about": "About Vitrin",
        "menu.showNow": "Show windows now",
        "menu.accessibility": "Accessibility settings",
        "menu.screenRecording": "Screen recording settings",
        "menu.retryTap": "Retry keyboard listening",
        "menu.quit": "Quit",
        "status.ax": "Accessibility",
        "status.sr": "Screen recording",
        "status.tap": "Listening",

        "tab.general": "General",
        "tab.appearance": "Appearance",
        "tab.motion": "Motion",
        "tab.glass": "Glass",
        "tab.transition": "Transition",
        "tab.about": "About",

        "general.trigger": "Trigger key",
        "general.trigger.note": "Hold this key and press Tab. On PC-layout keyboards the physical Alt key usually sends Command.",
        "general.language": "Language",
        "general.login": "Launch at login",
        "general.login.approval": "macOS is waiting for your approval: open System Settings › General › Login Items and enable Vitrin.",
        "general.login.note": "Vitrin starts silently in the background at login; no window opens.",
        "general.minimized": "List minimized windows",
        "general.titles": "Show window titles",
        "general.footer": "Show hint bar",
        "general.icon": "Show menu bar icon",
        "general.icon.note": "With the icon hidden you can reach settings three ways: press comma while the switcher is open, reopen Vitrin from Finder, or run open -a Vitrin.",
        "general.hide.title": "Hide the menu bar icon?",
        "general.hide.body": "Once the icon is gone you can reach settings by:\n\n• Pressing comma ( , ) while the switcher is open\n• Reopening Vitrin from Finder\n• Running: open -a Vitrin\n\nUse the button at the bottom of this window to quit.",
        "general.hide.ok": "Hide",

        "appearance.layout": "Layout",
        "appearance.entrance": "Entrance",
        "appearance.cellWidth": "Card width",
        "appearance.thumbHeight": "Preview height",
        "appearance.columns": "Max columns",
        "appearance.rows": "Max rows",
        "appearance.material": "Backdrop",
        "appearance.opacity": "Panel transparency",
        "appearance.shadow": "Panel shadow",
        "appearance.corner": "Corner radius",
        "appearance.op.zero": "Fully transparent — cards float directly over the desktop.",
        "appearance.op.mid": "Semi-transparent; windows behind stay readable.",
        "appearance.op.full": "Full material backdrop — the most legible.",

        "motion.character": "Character",
        "motion.stagger": "Stagger card entrance",
        "motion.glow": "Selection glow",
        "motion.flight": "Fly to selected window",
        "motion.n.none": "All animation off — fastest response.",
        "motion.n.snappy": "Short and crisp; best for fast Tab presses.",
        "motion.n.spring": "Spring with a slight overshoot. Default.",
        "motion.n.smooth": "Smooth easing, no overshoot.",
        "motion.n.dramatic": "Longer durations, pronounced overshoot.",

        "glass.frosted": "Frosted entrance",
        "glass.frosted.note": "Cards start blurred and sharpen — like frosted glass sliding away.",
        "glass.strength": "Frost strength",
        "glass.cards": "Glass card surfaces",
        "glass.depth": "Depth of field",
        "glass.depth.note": "Cards farther from the selection lose focus slightly.",
        "glass.sheen": "Specular sweep",
        "glass.reflection": "Reflection",
        "glass.tint": "Tint from window",
        "glass.tint.note": "The selected card's border and glow use that window's dominant color.",

        "transition.scrim": "Dim the background",
        "transition.dim": "Dim amount",
        "transition.blur": "Blur the background",
        "transition.scrim.note": "The real desktop blurs; no screenshot is taken.",
        "transition.pulse": "Arrival pulse",
        "transition.pulse.note": "The thumbnail lands on the target window, then a lit frame pulses once around it.",
        "transition.collapse": "Collapse panel into selection",
        "transition.parallax": "Pointer parallax tilt",
        "transition.parallax.note": "The panel tilts slightly toward the pointer.",

        "common.preview": "Preview",
        "common.reset": "Reset defaults",
        "common.quit": "Quit Vitrin",
        "common.cancel": "Cancel",
        "common.done": "Done",
        "quit.title": "Quit Vitrin?",
        "quit.body": "The switcher stops and the shortcut will not work. You will need to open Vitrin from Finder to start it again.",

        "switcher.all": "all windows",
        "switcher.sameApp": "same app",
        "switcher.count": "windows",
        "hint.forward": "forward",
        "hint.back": "back",
        "hint.sameApp": "same app",
        "hint.close": "close",
        "hint.minimize": "minimize",
        "hint.settings": "settings",
        "hint.cancel": "cancel",

        "about.subtitle": "Window-level switcher",
        "about.version": "Version",
        "about.what": "What it does",
        "about.what.body": "It selects windows, not apps. Multiple windows of one app are listed separately, each with its own live preview.",
        "about.how": "How it works",
        "about.how.body": "The shortcut is captured with a CGEvent tap. Windows come from CGWindowList, minimized ones from the Accessibility API. Previews are captured in parallel with ScreenCaptureKit.",
        "about.perms": "Required permissions",
        "about.perms.body": "Accessibility: to hear the shortcut and raise windows. Screen recording: for titles and previews.",
        "about.license": "License",
        "about.license.body": "GNU General Public License v3.0. Free to use, study, modify and share; derived works must stay open under the same licence.",
        "about.source": "Source code",
        "about.copy": "Copy version",
        "about.author": "Design and development",

        "layout.grid": "Grid",
        "layout.filmstrip": "Filmstrip",
        "layout.coverflow": "Coverflow",
        "layout.radial": "Fan",
        "layout.book": "Book",
        "layout.grid.n": "Everything at once; the most legible with many windows",
        "layout.filmstrip.n": "A single row; the selected card grows in the centre",
        "layout.coverflow.n": "Cards rotated in 3D; the selected one comes forward",
        "layout.radial.n": "Cards are arranged along an arc",
        "layout.book.n": "Like turning pages; passed cards fall to the left cover",

        "motion.none": "Off",
        "motion.snappy": "Snappy",
        "motion.spring": "Springy",
        "motion.smooth": "Smooth",
        "motion.dramatic": "Dramatic",

        "entrance.rise": "Rise",
        "entrance.fold": "Unfold",
        "entrance.flip": "Flip",
        "entrance.rise.n": "Cards rise slightly from below and sharpen.",
        "entrance.fold.n": "Like a foldable phone opening; cards flatten from their left edge.",
        "entrance.flip.n": "Cards arrive by flipping on their own axis.",

        "material.hud": "HUD",
        "material.dark": "Dark",
        "material.ultraThin": "Ultra thin",
        "material.sidebar": "Sidebar",

        "alert.ax.title": "Accessibility permission required",
        "alert.ax.body": "Vitrin needs Accessibility permission to capture the shortcut. It activates by itself once granted; if not, quit from the menu bar and reopen.",
        "alert.tap.title": "Could not listen for keyboard events",
        "alert.tap.body": "The CGEvent tap could not be created. If Vitrin is listed under Accessibility, remove the entry with (–), quit the app, reopen it and grant permission again.",
        "alert.openSettings": "Open settings",
        "alert.later": "Later",
        "alert.close": "Close"
    ]
}