extension Strings {
    static let pt: [String: String] = [
        "menu.settings": "Ajustes…",
        "menu.about": "Sobre o Vitrin",
        "menu.showNow": "Mostrar janelas agora",
        "menu.accessibility": "Ajustes de acessibilidade",
        "menu.screenRecording": "Ajustes de gravação de tela",
        "menu.retryTap": "Tentar escutar o teclado novamente",
        "menu.quit": "Encerrar",
        "status.ax": "Acessibilidade",
        "status.sr": "Gravação de tela",
        "status.tap": "Escuta",

        "tab.general": "Geral",
        "tab.appearance": "Aparência",
        "tab.motion": "Movimento",
        "tab.glass": "Vidro",
        "tab.transition": "Transição",
        "tab.about": "Sobre",

        "general.trigger": "Tecla de acionamento",
        "general.trigger.note": "Mantenha esta tecla pressionada e aperte Tab. Em teclados com layout de PC, a tecla Alt física costuma enviar Command.",
        "general.language": "Idioma",
        "general.login": "Abrir ao iniciar sessão",
        "general.login.approval": "O macOS aguarda a sua aprovação: abra Ajustes do Sistema › Geral › Itens de início e ative o Vitrin.",
        "general.login.note": "O Vitrin inicia silenciosamente em segundo plano ao iniciar a sessão; nenhuma janela é aberta.",
        "general.minimized": "Listar janelas minimizadas",
        "general.titles": "Mostrar títulos das janelas",
        "general.footer": "Mostrar a barra de dicas",
        "general.icon": "Mostrar ícone na barra de menus",
        "general.icon.note": "Com o ícone oculto você chega aos ajustes de três formas: apertar a vírgula com o seletor aberto, reabrir o Vitrin pelo Finder, ou executar open -a Vitrin.",
        "general.hide.title": "Ocultar o ícone da barra de menus?",
        "general.hide.body": "Sem o ícone, chegue aos ajustes assim:\n\n• Aperte a vírgula ( , ) com o seletor aberto\n• Reabra o Vitrin pelo Finder\n• Execute: open -a Vitrin\n\nUse o botão na parte inferior desta janela para encerrar.",
        "general.hide.ok": "Ocultar",

        "appearance.layout": "Disposição",
        "appearance.entrance": "Entrada",
        "appearance.cellWidth": "Largura do cartão",
        "appearance.thumbHeight": "Altura da prévia",
        "appearance.columns": "Colunas máx.",
        "appearance.rows": "Linhas máx.",
        "appearance.material": "Fundo",
        "appearance.opacity": "Transparência do painel",
        "appearance.shadow": "Sombra do painel",
        "appearance.corner": "Raio dos cantos",
        "appearance.op.zero": "Totalmente transparente: os cartões flutuam direto sobre a mesa.",
        "appearance.op.mid": "Semitransparente; as janelas atrás continuam legíveis.",
        "appearance.op.full": "Material completo: a opção mais legível.",

        "motion.character": "Caráter",
        "motion.stagger": "Entrada escalonada dos cartões",
        "motion.glow": "Brilho da seleção",
        "motion.flight": "Voo até a janela escolhida",
        "motion.n.none": "Sem animações: resposta mais rápida.",
        "motion.n.snappy": "Curto e seco; ideal para toques rápidos em Tab.",
        "motion.n.spring": "Mola com leve excesso. Padrão.",
        "motion.n.smooth": "Suavização macia, sem excesso.",
        "motion.n.dramatic": "Durações longas, excesso marcante.",

        "glass.frosted": "Entrada em vidro fosco",
        "glass.frosted.note": "Os cartões começam desfocados e ganham nitidez, como um vidro fosco que desliza para o lado.",
        "glass.strength": "Intensidade do fosco",
        "glass.cards": "Cartões de vidro",
        "glass.depth": "Profundidade de campo",
        "glass.depth.note": "Cartões mais distantes da seleção perdem um pouco de foco.",
        "glass.sheen": "Brilho especular",
        "glass.reflection": "Reflexo",
        "glass.tint": "Cor vinda da janela",
        "glass.tint.note": "A borda e o brilho do cartão selecionado usam a cor dominante daquela janela.",

        "transition.scrim": "Escurecer o fundo",
        "transition.dim": "Escurecimento",
        "transition.blur": "Desfocar o fundo",
        "transition.scrim.note": "A mesa real é desfocada; nenhuma captura de tela é feita.",
        "transition.pulse": "Pulso de chegada",
        "transition.pulse.note": "A miniatura pousa sobre a janela de destino e então um quadro luminoso pulsa uma vez ao redor.",
        "transition.collapse": "Recolher o painel para a seleção",
        "transition.parallax": "Inclinação de paralaxe com o ponteiro",
        "transition.parallax.note": "O painel se inclina levemente na direção do ponteiro.",

        "common.preview": "Pré-visualizar",
        "common.reset": "Restaurar padrões",
        "common.quit": "Encerrar o Vitrin",
        "common.cancel": "Cancelar",
        "common.done": "OK",
        "quit.title": "Encerrar o Vitrin?",
        "quit.body": "O seletor para e o atalho deixará de funcionar. Você precisará abrir o Vitrin pelo Finder para iniciá-lo de novo.",

        "switcher.all": "todas as janelas",
        "switcher.sameApp": "mesmo app",
        "switcher.count": "janelas",
        "hint.forward": "avançar",
        "hint.back": "voltar",
        "hint.sameApp": "mesmo app",
        "hint.close": "fechar",
        "hint.minimize": "minimizar",
        "hint.settings": "ajustes",
        "hint.cancel": "cancelar",

        "about.subtitle": "Seletor no nível das janelas",
        "about.version": "Versão",
        "about.what": "O que faz",
        "about.what.body": "Ele seleciona janelas, não apps. Várias janelas de um mesmo app aparecem separadamente, cada uma com sua prévia ao vivo.",
        "about.how": "Como funciona",
        "about.how.body": "O atalho é capturado com um CGEvent tap. As janelas vêm do CGWindowList e as minimizadas da API de acessibilidade. As prévias são capturadas em paralelo com o ScreenCaptureKit.",
        "about.perms": "Permissões necessárias",
        "about.perms.body": "Acessibilidade: para ouvir o atalho e trazer janelas para a frente. Gravação de tela: para títulos e prévias.",
        "about.copy": "Copiar versão",
        "about.author": "Design e desenvolvimento",

        "layout.grid": "Grade",
        "layout.filmstrip": "Tira de filme",
        "layout.coverflow": "Coverflow",
        "layout.radial": "Leque",
        "layout.book": "Livro",
        "layout.grid.n": "Tudo de uma vez; o mais legível com muitas janelas",
        "layout.filmstrip.n": "Uma única fileira; o cartão escolhido cresce no centro",
        "layout.coverflow.n": "Cartões girados em 3D; o escolhido vem à frente",
        "layout.radial.n": "Os cartões ficam dispostos ao longo de um arco",
        "layout.book.n": "Como virar páginas; os cartões passados caem à esquerda",

        "motion.none": "Desativado",
        "motion.snappy": "Ágil",
        "motion.spring": "Com mola",
        "motion.smooth": "Suave",
        "motion.dramatic": "Marcante",

        "entrance.rise": "Subida",
        "entrance.fold": "Desdobrar",
        "entrance.flip": "Virada",
        "entrance.rise.n": "Os cartões sobem levemente e ganham nitidez.",
        "entrance.fold.n": "Como um telefone dobrável abrindo; os cartões se abrem pela borda esquerda.",
        "entrance.flip.n": "Os cartões chegam girando no próprio eixo.",

        "material.hud": "HUD",
        "material.dark": "Escuro",
        "material.ultraThin": "Vidro fino",
        "material.sidebar": "Barra lateral",

        "alert.ax.title": "Permissão de acessibilidade necessária",
        "alert.ax.body": "O Vitrin precisa da permissão de acessibilidade para capturar o atalho. Ele se ativa sozinho assim que a permissão for concedida; caso contrário, encerre pela barra de menus e abra novamente.",
        "alert.tap.title": "Não foi possível escutar os eventos de teclado",
        "alert.tap.body": "Não foi possível criar o CGEvent tap. Se o Vitrin estiver listado em Acessibilidade, remova a entrada com (–), encerre o app, abra de novo e conceda a permissão outra vez.",
        "alert.openSettings": "Abrir ajustes",
        "alert.later": "Depois",
        "alert.close": "Fechar"
    ]
}
