// Vitrin — macOS window-level switcher
// Copyright (C) 2026 Çağlar Ülküderner
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version. See <https://www.gnu.org/licenses/> for details.
//
// https://github.com/ulkuderner/vitrin

extension Strings {
    static let de: [String: String] = [
        "menu.settings": "Einstellungen…",
        "menu.about": "Über Vitrin",
        "menu.showNow": "Fenster jetzt anzeigen",
        "menu.accessibility": "Bedienungshilfen-Einstellungen",
        "menu.screenRecording": "Bildschirmaufnahme-Einstellungen",
        "menu.retryTap": "Tastaturerfassung erneut versuchen",
        "menu.quit": "Beenden",
        "status.ax": "Bedienungshilfen",
        "status.sr": "Bildschirmaufnahme",
        "status.tap": "Erfassung",

        "tab.general": "Allgemein",
        "tab.appearance": "Darstellung",
        "tab.motion": "Bewegung",
        "tab.glass": "Glas",
        "tab.transition": "Übergang",
        "tab.about": "Über",

        "general.trigger": "Auslösetaste",
        "general.trigger.note": "Halte diese Taste gedrückt und drücke Tab. Auf Tastaturen mit PC-Layout sendet die physische Alt-Taste meist Command.",
        "general.language": "Sprache",
        "general.login": "Beim Anmelden starten",
        "general.login.approval": "macOS wartet auf deine Bestätigung: Systemeinstellungen › Allgemein › Anmeldeobjekte öffnen und Vitrin aktivieren.",
        "general.login.note": "Vitrin startet bei der Anmeldung unbemerkt im Hintergrund; es öffnet sich kein Fenster.",
        "general.minimized": "Minimierte Fenster auflisten",
        "general.titles": "Fenstertitel anzeigen",
        "general.footer": "Hinweisleiste anzeigen",
        "general.icon": "Menüleistensymbol anzeigen",
        "general.icon.note": "Bei ausgeblendetem Symbol erreichst du die Einstellungen auf drei Wegen: Komma drücken, während der Umschalter offen ist, Vitrin im Finder erneut öffnen oder open -a Vitrin ausführen.",
        "general.hide.title": "Menüleistensymbol ausblenden?",
        "general.hide.body": "Ohne Symbol erreichst du die Einstellungen so:\n\n• Komma ( , ) drücken, während der Umschalter offen ist\n• Vitrin im Finder erneut öffnen\n• Im Terminal: open -a Vitrin\n\nZum Beenden dient die Taste unten in diesem Fenster.",
        "general.hide.ok": "Ausblenden",

        "appearance.layout": "Anordnung",
        "appearance.entrance": "Einblendung",
        "appearance.cellWidth": "Kartenbreite",
        "appearance.thumbHeight": "Vorschauhöhe",
        "appearance.columns": "Max. Spalten",
        "appearance.rows": "Max. Zeilen",
        "appearance.material": "Hintergrund",
        "appearance.opacity": "Transparenz des Panels",
        "appearance.shadow": "Panel-Schatten",
        "appearance.corner": "Eckenradius",
        "appearance.op.zero": "Vollständig transparent — die Karten schweben direkt über dem Schreibtisch.",
        "appearance.op.mid": "Halbtransparent; dahinterliegende Fenster bleiben erkennbar.",
        "appearance.op.full": "Volles Material — am besten lesbar.",

        "motion.character": "Charakter",
        "motion.stagger": "Karten nacheinander einblenden",
        "motion.glow": "Auswahl-Leuchten",
        "motion.flight": "Flug zum gewählten Fenster",
        "motion.n.none": "Alle Animationen aus — schnellste Reaktion.",
        "motion.n.snappy": "Kurz und knapp; ideal bei schnellen Tab-Anschlägen.",
        "motion.n.spring": "Feder mit leichtem Überschwingen. Standard.",
        "motion.n.smooth": "Weiches Easing, kein Überschwingen.",
        "motion.n.dramatic": "Längere Dauer, deutliches Überschwingen.",

        "glass.frosted": "Milchglas-Einblendung",
        "glass.frosted.note": "Die Karten beginnen unscharf und werden klar — als würde Milchglas beiseitegleiten.",
        "glass.strength": "Mattierungsstärke",
        "glass.cards": "Karten aus Glas",
        "glass.depth": "Schärfentiefe",
        "glass.depth.note": "Karten weiter von der Auswahl entfernt verlieren leicht an Schärfe.",
        "glass.sheen": "Lichtreflex",
        "glass.reflection": "Spiegelung",
        "glass.tint": "Farbe aus dem Fenster",
        "glass.tint.note": "Rahmen und Leuchten der gewählten Karte übernehmen die dominante Farbe des Fensters.",

        "transition.scrim": "Hintergrund abdunkeln",
        "transition.dim": "Abdunklung",
        "transition.blur": "Hintergrund weichzeichnen",
        "transition.scrim.note": "Der echte Schreibtisch wird weichgezeichnet; es wird kein Bildschirmfoto erstellt.",
        "transition.pulse": "Ankunftsimpuls",
        "transition.pulse.note": "Die Vorschau landet auf dem Zielfenster, danach pulsiert ein leuchtender Rahmen einmal darum.",
        "transition.collapse": "Panel in die Auswahl zusammenziehen",
        "transition.parallax": "Parallaxe-Neigung mit dem Zeiger",
        "transition.parallax.note": "Das Panel neigt sich leicht in Richtung des Zeigers.",

        "common.preview": "Vorschau",
        "common.reset": "Standardwerte",
        "common.quit": "Vitrin beenden",
        "common.cancel": "Abbrechen",
        "common.done": "Fertig",
        "quit.title": "Vitrin beenden?",
        "quit.body": "Der Umschalter stoppt und das Tastaturkürzel funktioniert nicht mehr. Zum Neustart musst du Vitrin im Finder öffnen.",

        "switcher.all": "alle Fenster",
        "switcher.sameApp": "gleiche App",
        "switcher.count": "Fenster",
        "hint.forward": "vorwärts",
        "hint.back": "zurück",
        "hint.sameApp": "gleiche App",
        "hint.close": "schließen",
        "hint.minimize": "minimieren",
        "hint.settings": "Einstellungen",
        "hint.cancel": "abbrechen",

        "about.subtitle": "Umschalter auf Fensterebene",
        "about.version": "Version",
        "about.what": "Was es tut",
        "about.what.body": "Es wählt Fenster aus, keine Apps. Mehrere Fenster einer App werden einzeln aufgeführt, jedes mit eigener Live-Vorschau.",
        "about.how": "Wie es funktioniert",
        "about.how.body": "Das Kürzel wird über einen CGEvent-Tap erfasst. Fenster stammen aus CGWindowList, minimierte aus der Accessibility-API. Vorschauen entstehen parallel mit ScreenCaptureKit.",
        "about.perms": "Erforderliche Berechtigungen",
        "about.perms.body": "Bedienungshilfen: um das Kürzel zu hören und Fenster nach vorn zu holen. Bildschirmaufnahme: für Titel und Vorschauen.",
        "about.copy": "Version kopieren",
        "about.author": "Design und Entwicklung",

        "layout.grid": "Raster",
        "layout.filmstrip": "Filmstreifen",
        "layout.coverflow": "Coverflow",
        "layout.radial": "Fächer",
        "layout.book": "Buch",
        "layout.grid.n": "Alles auf einmal; bei vielen Fenstern am besten lesbar",
        "layout.filmstrip.n": "Eine Reihe; die gewählte Karte wächst in der Mitte",
        "layout.coverflow.n": "In 3D gedrehte Karten; die gewählte tritt hervor",
        "layout.radial.n": "Die Karten liegen auf einem Bogen",
        "layout.book.n": "Wie Umblättern; passierte Karten fallen auf den linken Deckel",

        "motion.none": "Aus",
        "motion.snappy": "Knackig",
        "motion.spring": "Federnd",
        "motion.smooth": "Weich",
        "motion.dramatic": "Ausladend",

        "entrance.rise": "Aufsteigen",
        "entrance.fold": "Aufklappen",
        "entrance.flip": "Umklappen",
        "entrance.rise.n": "Die Karten steigen leicht von unten auf und werden scharf.",
        "entrance.fold.n": "Wie ein faltbares Telefon; die Karten klappen von der linken Kante auf.",
        "entrance.flip.n": "Die Karten kippen um ihre eigene Achse herein.",

        "material.hud": "HUD",
        "material.dark": "Dunkel",
        "material.ultraThin": "Dünnes Glas",
        "material.sidebar": "Seitenleiste",

        "alert.ax.title": "Bedienungshilfen-Berechtigung erforderlich",
        "alert.ax.body": "Vitrin benötigt die Bedienungshilfen-Berechtigung, um das Kürzel zu erfassen. Nach der Freigabe wird es von selbst aktiv; andernfalls über die Menüleiste beenden und erneut öffnen.",
        "alert.tap.title": "Tastaturereignisse konnten nicht erfasst werden",
        "alert.tap.body": "Der CGEvent-Tap konnte nicht erstellt werden. Falls Vitrin unter Bedienungshilfen aufgeführt ist, entferne den Eintrag mit (–), beende die App, öffne sie erneut und erteile die Berechtigung neu.",
        "alert.openSettings": "Einstellungen öffnen",
        "alert.later": "Später",
        "alert.close": "Schließen"
    ]
}