extension Strings {
    static let tr: [String: String] = [
        "menu.settings": "Ayarlar…",
        "menu.about": "Vitrin Hakkında",
        "menu.showNow": "Pencereleri şimdi göster",
        "menu.accessibility": "Erişilebilirlik ayarları",
        "menu.screenRecording": "Ekran kaydı ayarları",
        "menu.retryTap": "Klavye dinlemeyi yeniden dene",
        "menu.quit": "Çık",
        "status.ax": "Erişilebilirlik",
        "status.sr": "Ekran kaydı",
        "status.tap": "Dinleme",

        "tab.general": "Genel",
        "tab.appearance": "Görünüm",
        "tab.motion": "Hareket",
        "tab.glass": "Cam",
        "tab.transition": "Geçiş",
        "tab.about": "Hakkında",

        "general.trigger": "Tetikleyici",
        "general.trigger.note": "Bu tuşu basılı tutup Tab'a bas. Windows düzeni klavyelerde fiziksel Alt tuşu genelde Command gönderir.",
        "general.language": "Dil",
        "general.login": "Açılışta otomatik başlat",
        "general.login.approval": "macOS onayını bekliyor: Sistem Ayarları › Genel › Giriş Öğeleri bölümünden Vitrin'i etkinleştir.",
        "general.login.note": "Oturum açıldığında Vitrin sessizce arka planda başlar; hiçbir pencere açılmaz.",
        "general.minimized": "Küçültülmüş pencereleri listele",
        "general.titles": "Pencere başlıklarını göster",
        "general.footer": "Alt bilgi şeridini göster",
        "general.icon": "Menü çubuğu ikonunu göster",
        "general.icon.note": "İkon kapalıyken ayarlara üç yoldan dönebilirsin: anahtarlayıcı açıkken virgül tuşu, Finder'dan Vitrin'i yeniden açmak, ya da terminalde open -a Vitrin.",
        "general.hide.title": "Menü çubuğu ikonu gizlensin mi?",
        "general.hide.body": "İkon kaybolduğunda ayarlara şu yollarla dönebilirsin:\n\n• Anahtarlayıcı açıkken virgül ( , ) tuşuna bas\n• Finder'dan Vitrin'i yeniden aç\n• Terminalde: open -a Vitrin\n\nÇıkmak için bu pencerenin altındaki düğmeyi kullan.",
        "general.hide.ok": "Gizle",

        "appearance.layout": "Diziliş",
        "appearance.entrance": "Giriş",
        "appearance.cellWidth": "Kart genişliği",
        "appearance.thumbHeight": "Önizleme yüksekliği",
        "appearance.columns": "En fazla sütun",
        "appearance.rows": "En fazla satır",
        "appearance.material": "Arka plan",
        "appearance.opacity": "Taşıyıcı panel saydamlığı",
        "appearance.shadow": "Panel gölgesi",
        "appearance.corner": "Köşe yuvarlaklığı",
        "appearance.op.zero": "Panel tamamen saydam — kartlar doğrudan masaüstünde yüzer.",
        "appearance.op.mid": "Zemin yarı saydam; arkadaki pencereler seçilebilir kalır.",
        "appearance.op.full": "Tam malzeme zemini — en okunaklısı.",

        "motion.character": "Karakter",
        "motion.stagger": "Kartlar sırayla belirsin",
        "motion.glow": "Seçim parlaması",
        "motion.flight": "Seçilen pencereye uçuş",
        "motion.n.none": "Tüm animasyonlar kapalı — en hızlı tepki.",
        "motion.n.snappy": "Kısa ve sert; hızlı Tab basışlarında en iyi his.",
        "motion.n.spring": "Hafif overshoot'lu yay. Varsayılan.",
        "motion.n.smooth": "Yumuşak easing, overshoot yok.",
        "motion.n.dramatic": "Uzun süreler, belirgin overshoot.",

        "glass.frosted": "Buzlu cam girişi",
        "glass.frosted.note": "Kartlar bulanık başlayıp netleşir — buzlu camdan bakıp cam çekilirken netlenmesi gibi.",
        "glass.strength": "Buz yoğunluğu",
        "glass.cards": "Cam yüzeyli kartlar",
        "glass.depth": "Alan derinliği",
        "glass.depth.note": "Seçiliden uzaklaşan kartlar hafifçe odağını kaybeder.",
        "glass.sheen": "Parıltı geçişi",
        "glass.reflection": "Yansıma",
        "glass.tint": "Rengi pencereden al",
        "glass.tint.note": "Seçili kartın çerçevesi ve parıltısı o pencerenin baskın rengini kullanır.",

        "transition.scrim": "Arka planı karart",
        "transition.dim": "Kararma",
        "transition.blur": "Arka planı bulanıklaştır",
        "transition.scrim.note": "Gerçek masaüstü bulanıklaşır; ekran görüntüsü alınmaz.",
        "transition.pulse": "Varış parıltısı",
        "transition.pulse.note": "Küçük resim gittiği pencerenin üzerine konar, ardından çevresinde bir kez ışıklı çerçeve atar.",
        "transition.collapse": "Panel seçime büzülerek kapansın",
        "transition.parallax": "Fareyle paralaks eğim",
        "transition.parallax.note": "Panel imlecin bulunduğu yöne doğru hafifçe eğilir.",

        "common.preview": "Önizle",
        "common.reset": "Varsayılanlara dön",
        "common.quit": "Vitrin'den çık",
        "common.cancel": "Vazgeç",
        "common.done": "Bitti",
        "quit.title": "Vitrin'den çıkılsın mı?",
        "quit.body": "Anahtarlayıcı kapanır ve kısayol çalışmaz. Yeniden başlatmak için Finder'dan Vitrin'i açman gerekir.",

        "switcher.all": "tüm pencereler",
        "switcher.sameApp": "aynı uygulama",
        "switcher.count": "pencere",
        "hint.forward": "ileri",
        "hint.back": "geri",
        "hint.sameApp": "aynı uygulama",
        "hint.close": "kapat",
        "hint.minimize": "küçült",
        "hint.settings": "ayarlar",
        "hint.cancel": "iptal",

        "about.subtitle": "Pencere bazlı anahtarlayıcı",
        "about.version": "Sürüm",
        "about.what": "Ne yapar",
        "about.what.body": "Uygulama değil pencere seçer. Aynı uygulamanın birden çok penceresi ayrı ayrı listelenir, her biri kendi canlı görüntüsüyle.",
        "about.how": "Nasıl çalışır",
        "about.how.body": "Kısayol CGEvent tap ile yakalanır. Pencere listesi CGWindowList'ten, küçültülmüşler Accessibility API'sinden gelir. Önizlemeler ScreenCaptureKit ile paralel yakalanır.",
        "about.perms": "Gerekli izinler",
        "about.perms.body": "Erişilebilirlik: kısayolu duymak ve pencereyi öne getirmek için. Ekran kaydı: başlıklar ve önizlemeler için.",
        "about.copy": "Sürümü kopyala",
        "about.author": "Tasarım ve geliştirme",

        "layout.grid": "Izgara",
        "layout.filmstrip": "Şerit",
        "layout.coverflow": "Coverflow",
        "layout.radial": "Yelpaze",
        "layout.book": "Kitap",
        "layout.grid.n": "Hepsi bir arada, çok pencerede en okunaklısı",
        "layout.filmstrip.n": "Tek sıra, seçili olan ortada büyür",
        "layout.coverflow.n": "3B döndürülmüş kartlar, seçili öne çıkar",
        "layout.radial.n": "Kartlar bir yay üzerine dizilir",
        "layout.book.n": "Sayfa çevirir gibi; geçilenler sol kapağa düşer",

        "motion.none": "Kapalı",
        "motion.snappy": "Keskin",
        "motion.spring": "Yaylı",
        "motion.smooth": "Yumuşak",
        "motion.dramatic": "Gösterişli",

        "entrance.rise": "Yükselerek",
        "entrance.fold": "Katlanarak",
        "entrance.flip": "Çevrilerek",
        "entrance.rise.n": "Kartlar hafifçe aşağıdan yükselip netleşir.",
        "entrance.fold.n": "Katlanabilir telefon açılır gibi; kartlar sol kenarından düzleşir.",
        "entrance.flip.n": "Kartlar kendi ekseninde çevrilerek gelir.",

        "material.hud": "HUD",
        "material.dark": "Koyu",
        "material.ultraThin": "İnce cam",
        "material.sidebar": "Kenar çubuğu",

        "alert.ax.title": "Erişilebilirlik izni gerekli",
        "alert.ax.body": "Vitrin kısayolu yakalayabilmek için Erişilebilirlik iznine ihtiyaç duyuyor. İzni verdikten sonra kendiliğinden devreye girer; girmezse menü çubuğundan çıkıp yeniden açın.",
        "alert.tap.title": "Klavye olayları dinlenemedi",
        "alert.tap.body": "CGEvent tap oluşturulamadı. Erişilebilirlik listesinde Vitrin varsa işaretini kaldırıp (–) ile tamamen silin, uygulamadan çıkın, yeniden açıp izni baştan verin.",
        "alert.openSettings": "Ayarları aç",
        "alert.later": "Sonra",
        "alert.close": "Kapat"
    ]
}
