// Vitrin — macOS window-level switcher
// Copyright (C) 2026 Çağlar Ülküderner
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version. See <https://www.gnu.org/licenses/> for details.
//
// https://github.com/ulkuderner/vitrin

extension Strings {
    static let pl: [String: String] = [
        "menu.settings": "Ustawienia…",
        "menu.about": "Vitrin — informacje",
        "menu.showNow": "Pokaż okna teraz",
        "menu.accessibility": "Ustawienia dostępności",
        "menu.screenRecording": "Ustawienia nagrywania ekranu",
        "menu.retryTap": "Ponów nasłuch klawiatury",
        "menu.quit": "Zakończ",
        "status.ax": "Dostępność",
        "status.sr": "Nagrywanie ekranu",
        "status.tap": "Nasłuch",

        "tab.general": "Ogólne",
        "tab.appearance": "Wygląd",
        "tab.motion": "Ruch",
        "tab.glass": "Szkło",
        "tab.transition": "Przejście",
        "tab.about": "Informacje",

        "general.trigger": "Klawisz wyzwalający",
        "general.trigger.note": "Przytrzymaj ten klawisz i naciśnij Tab. Na klawiaturach w układzie PC fizyczny klawisz Alt zwykle wysyła Command.",
        "general.language": "Język",
        "general.login": "Uruchamiaj przy logowaniu",
        "general.login.approval": "macOS czeka na Twoją zgodę: otwórz Ustawienia systemowe › Ogólne › Elementy logowania i włącz Vitrin.",
        "general.login.note": "Vitrin uruchamia się przy logowaniu po cichu w tle; żadne okno się nie otwiera.",
        "general.minimized": "Pokazuj zminimalizowane okna",
        "general.titles": "Pokazuj tytuły okien",
        "general.footer": "Pokazuj pasek podpowiedzi",
        "general.icon": "Pokazuj ikonę na pasku menu",
        "general.icon.note": "Przy ukrytej ikonie ustawienia otworzysz na trzy sposoby: naciśnij przecinek przy otwartym przełączniku, otwórz Vitrin ponownie z Findera lub uruchom open -a Vitrin.",
        "general.hide.title": "Ukryć ikonę na pasku menu?",
        "general.hide.body": "Bez ikony ustawienia otworzysz tak:\n\n• Naciśnij przecinek ( , ) przy otwartym przełączniku\n• Otwórz Vitrin ponownie z Findera\n• Uruchom: open -a Vitrin\n\nDo zakończenia służy przycisk na dole tego okna.",
        "general.hide.ok": "Ukryj",

        "appearance.layout": "Układ",
        "appearance.entrance": "Wejście",
        "appearance.cellWidth": "Szerokość karty",
        "appearance.thumbHeight": "Wysokość podglądu",
        "appearance.columns": "Maks. kolumn",
        "appearance.rows": "Maks. wierszy",
        "appearance.material": "Tło",
        "appearance.opacity": "Przezroczystość panelu",
        "appearance.shadow": "Cień panelu",
        "appearance.corner": "Promień narożników",
        "appearance.op.zero": "Całkowicie przezroczysty — karty unoszą się bezpośrednio nad biurkiem.",
        "appearance.op.mid": "Półprzezroczysty; okna z tyłu pozostają czytelne.",
        "appearance.op.full": "Pełny materiał — najbardziej czytelny.",

        "motion.character": "Charakter",
        "motion.stagger": "Karty pojawiają się po kolei",
        "motion.glow": "Poświata zaznaczenia",
        "motion.flight": "Lot do wybranego okna",
        "motion.n.none": "Bez animacji — najszybsza reakcja.",
        "motion.n.snappy": "Krótko i ostro; najlepsze przy szybkim naciskaniu Tab.",
        "motion.n.spring": "Sprężyna z lekkim wychyleniem. Domyślne.",
        "motion.n.smooth": "Miękkie wygładzenie, bez wychylenia.",
        "motion.n.dramatic": "Dłuższy czas, wyraźne wychylenie.",

        "glass.frosted": "Wejście przez mleczne szkło",
        "glass.frosted.note": "Karty zaczynają rozmyte i wyostrzają się — jakby mleczne szkło odsuwało się na bok.",
        "glass.strength": "Siła zmatowienia",
        "glass.cards": "Szklane karty",
        "glass.depth": "Głębia ostrości",
        "glass.depth.note": "Karty dalsze od zaznaczenia lekko tracą ostrość.",
        "glass.sheen": "Refleks świetlny",
        "glass.reflection": "Odbicie",
        "glass.tint": "Kolor z okna",
        "glass.tint.note": "Obramowanie i poświata wybranej karty przyjmują dominujący kolor tego okna.",

        "transition.scrim": "Przyciemnij tło",
        "transition.dim": "Przyciemnienie",
        "transition.blur": "Rozmyj tło",
        "transition.scrim.note": "Rozmywane jest prawdziwe biurko; nie powstaje żaden zrzut ekranu.",
        "transition.pulse": "Puls przybycia",
        "transition.pulse.note": "Miniatura ląduje na oknie docelowym, po czym wokół niego raz pulsuje świetlna ramka.",
        "transition.collapse": "Zwijaj panel do zaznaczenia",
        "transition.parallax": "Pochylenie paralaksy za wskaźnikiem",
        "transition.parallax.note": "Panel pochyla się lekko w stronę wskaźnika.",

        "common.preview": "Podgląd",
        "common.reset": "Przywróć domyślne",
        "common.quit": "Zakończ Vitrin",
        "common.cancel": "Anuluj",
        "common.done": "Gotowe",
        "quit.title": "Zakończyć Vitrin?",
        "quit.body": "Przełącznik przestanie działać, a skrót nie będzie reagował. Aby uruchomić go ponownie, otwórz Vitrin z Findera.",

        "switcher.all": "wszystkie okna",
        "switcher.sameApp": "ta sama aplikacja",
        "switcher.count": "okien",
        "hint.forward": "dalej",
        "hint.back": "wstecz",
        "hint.sameApp": "ta sama aplikacja",
        "hint.close": "zamknij",
        "hint.minimize": "zminimalizuj",
        "hint.settings": "ustawienia",
        "hint.cancel": "anuluj",

        "about.subtitle": "Przełącznik na poziomie okien",
        "about.version": "Wersja",
        "about.what": "Co robi",
        "about.what.body": "Wybiera okna, nie aplikacje. Kilka okien jednej aplikacji jest wymienionych osobno, każde z własnym podglądem na żywo.",
        "about.how": "Jak działa",
        "about.how.body": "Skrót przechwytuje CGEvent tap. Okna pochodzą z CGWindowList, zminimalizowane z API dostępności. Podglądy powstają równolegle przez ScreenCaptureKit.",
        "about.perms": "Wymagane uprawnienia",
        "about.perms.body": "Dostępność: aby usłyszeć skrót i wysunąć okna na wierzch. Nagrywanie ekranu: dla tytułów i podglądów.",
        "about.copy": "Kopiuj wersję",
        "about.author": "Projekt i rozwój",

        "layout.grid": "Siatka",
        "layout.filmstrip": "Taśma filmowa",
        "layout.coverflow": "Coverflow",
        "layout.radial": "Wachlarz",
        "layout.book": "Książka",
        "layout.grid.n": "Wszystko naraz; najczytelniejsze przy wielu oknach",
        "layout.filmstrip.n": "Jeden rząd; wybrana karta rośnie na środku",
        "layout.coverflow.n": "Karty obrócone w 3D; wybrana wysuwa się do przodu",
        "layout.radial.n": "Karty ułożone wzdłuż łuku",
        "layout.book.n": "Jak przewracanie stron; minięte karty opadają na lewo",

        "motion.none": "Wyłączone",
        "motion.snappy": "Sprężyste",
        "motion.spring": "Elastyczne",
        "motion.smooth": "Płynne",
        "motion.dramatic": "Efektowne",

        "entrance.rise": "Wznoszenie",
        "entrance.fold": "Rozkładanie",
        "entrance.flip": "Obrót",
        "entrance.rise.n": "Karty unoszą się lekko z dołu i wyostrzają.",
        "entrance.fold.n": "Jak otwierający się składany telefon; karty rozkładają się od lewej krawędzi.",
        "entrance.flip.n": "Karty pojawiają się, obracając się wokół własnej osi.",

        "material.hud": "HUD",
        "material.dark": "Ciemne",
        "material.ultraThin": "Cienkie szkło",
        "material.sidebar": "Panel boczny",

        "alert.ax.title": "Wymagane uprawnienie dostępności",
        "alert.ax.body": "Vitrin potrzebuje uprawnienia dostępności, aby przechwycić skrót. Po jego przyznaniu włącza się sam; jeśli nie, zakończ z paska menu i otwórz ponownie.",
        "alert.tap.title": "Nie udało się nasłuchiwać zdarzeń klawiatury",
        "alert.tap.body": "Nie udało się utworzyć CGEvent tap. Jeśli Vitrin figuruje w Dostępności, usuń wpis przyciskiem (–), zakończ aplikację, otwórz ją ponownie i przyznaj uprawnienie od nowa.",
        "alert.openSettings": "Otwórz ustawienia",
        "alert.later": "Później",
        "alert.close": "Zamknij"
    ]
}