// Vitrin — macOS window-level switcher
// Copyright (C) 2026 Çağlar Ülküderner
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version. See <https://www.gnu.org/licenses/> for details.
//
// https://github.com/ulkuderner/vitrin

extension Strings {
    static let ko: [String: String] = [
        "menu.settings": "설정…",
        "menu.about": "Vitrin에 관하여",
        "menu.showNow": "지금 윈도우 보기",
        "menu.accessibility": "손쉬운 사용 설정",
        "menu.screenRecording": "화면 기록 설정",
        "menu.retryTap": "키보드 감지 다시 시도",
        "menu.quit": "종료",
        "status.ax": "손쉬운 사용",
        "status.sr": "화면 기록",
        "status.tap": "감지",

        "tab.general": "일반",
        "tab.appearance": "외관",
        "tab.motion": "모션",
        "tab.glass": "유리",
        "tab.transition": "전환",
        "tab.about": "정보",

        "general.trigger": "트리거 키",
        "general.trigger.note": "이 키를 누른 채 Tab을 누르십시오. PC 배열 키보드에서는 물리적인 Alt 키가 대개 Command를 보냅니다.",
        "general.language": "언어",
        "general.login": "로그인 시 실행",
        "general.login.approval": "macOS가 승인을 기다리고 있습니다. 시스템 설정 › 일반 › 로그인 항목에서 Vitrin을 켜십시오.",
        "general.login.note": "로그인하면 Vitrin이 백그라운드에서 조용히 시작합니다. 윈도우는 열리지 않습니다.",
        "general.minimized": "최소화된 윈도우도 표시",
        "general.titles": "윈도우 제목 표시",
        "general.footer": "힌트 막대 표시",
        "general.icon": "메뉴 막대 아이콘 표시",
        "general.icon.note": "아이콘을 숨겨도 설정으로 가는 방법이 세 가지 있습니다. 전환기가 열린 상태에서 쉼표를 누르거나, Finder에서 Vitrin을 다시 열거나, open -a Vitrin을 실행하십시오.",
        "general.hide.title": "메뉴 막대 아이콘을 숨기시겠습니까?",
        "general.hide.body": "아이콘이 사라진 뒤에는 이렇게 설정을 열 수 있습니다:\n\n• 전환기가 열린 상태에서 쉼표 ( , ) 누르기\n• Finder에서 Vitrin 다시 열기\n• 터미널에서: open -a Vitrin\n\n종료하려면 이 윈도우 아래쪽 버튼을 사용하십시오.",
        "general.hide.ok": "숨기기",

        "appearance.layout": "배치",
        "appearance.entrance": "등장",
        "appearance.cellWidth": "카드 너비",
        "appearance.thumbHeight": "미리보기 높이",
        "appearance.columns": "최대 열",
        "appearance.rows": "최대 행",
        "appearance.material": "배경",
        "appearance.opacity": "패널 투명도",
        "appearance.shadow": "패널 그림자",
        "appearance.corner": "모서리 반경",
        "appearance.op.zero": "완전히 투명 — 카드가 데스크탑 위에 그대로 떠 있습니다.",
        "appearance.op.mid": "반투명. 뒤쪽 윈도우도 알아볼 수 있습니다.",
        "appearance.op.full": "재질을 가득 채움 — 가장 잘 읽힙니다.",

        "motion.character": "성격",
        "motion.stagger": "카드를 차례로 표시",
        "motion.glow": "선택 발광",
        "motion.flight": "선택한 윈도우로 날아가기",
        "motion.n.none": "모든 애니메이션 끔 — 반응이 가장 빠릅니다.",
        "motion.n.snappy": "짧고 또렷하게. Tab을 빠르게 누를 때 가장 좋습니다.",
        "motion.n.spring": "살짝 넘치는 스프링. 기본값입니다.",
        "motion.n.smooth": "부드러운 이징, 넘침 없음.",
        "motion.n.dramatic": "긴 시간과 뚜렷한 넘침.",

        "glass.frosted": "성에 유리 등장",
        "glass.frosted.note": "카드가 흐릿하게 시작해 또렷해집니다. 성에 유리가 옆으로 미끄러지는 느낌입니다.",
        "glass.strength": "성에 강도",
        "glass.cards": "유리 재질 카드",
        "glass.depth": "피사계 심도",
        "glass.depth.note": "선택된 카드에서 멀어질수록 초점이 조금씩 흐려집니다.",
        "glass.sheen": "광택 스침",
        "glass.reflection": "반사",
        "glass.tint": "윈도우에서 색 가져오기",
        "glass.tint.note": "선택된 카드의 테두리와 발광이 그 윈도우의 주된 색을 사용합니다.",

        "transition.scrim": "배경 어둡게",
        "transition.dim": "어두운 정도",
        "transition.blur": "배경 흐리게",
        "transition.scrim.note": "실제 데스크탑이 흐려집니다. 스크린샷은 찍지 않습니다.",
        "transition.pulse": "도착 펄스",
        "transition.pulse.note": "미리보기가 대상 윈도우 위에 내려앉은 뒤, 그 주위에서 빛나는 테두리가 한 번 맥동합니다.",
        "transition.collapse": "패널을 선택한 카드로 접기",
        "transition.parallax": "포인터를 따르는 시차 기울기",
        "transition.parallax.note": "패널이 포인터 쪽으로 살짝 기울어집니다.",

        "common.preview": "미리보기",
        "common.reset": "기본값으로",
        "common.quit": "Vitrin 종료",
        "common.cancel": "취소",
        "common.done": "완료",
        "quit.title": "Vitrin을 종료하시겠습니까?",
        "quit.body": "전환기가 멈추고 단축키가 동작하지 않습니다. 다시 시작하려면 Finder에서 Vitrin을 열어야 합니다.",

        "switcher.all": "모든 윈도우",
        "switcher.sameApp": "같은 앱",
        "switcher.count": "개 윈도우",
        "hint.forward": "다음",
        "hint.back": "이전",
        "hint.sameApp": "같은 앱",
        "hint.close": "닫기",
        "hint.minimize": "최소화",
        "hint.settings": "설정",
        "hint.cancel": "취소",

        "about.subtitle": "윈도우 단위 전환기",
        "about.version": "버전",
        "about.what": "하는 일",
        "about.what.body": "앱이 아니라 윈도우를 고릅니다. 같은 앱의 여러 윈도우가 각각 따로, 저마다의 실시간 미리보기와 함께 나열됩니다.",
        "about.how": "작동 방식",
        "about.how.body": "단축키는 CGEvent tap으로 가로챕니다. 윈도우 목록은 CGWindowList에서, 최소화된 것은 손쉬운 사용 API에서 가져옵니다. 미리보기는 ScreenCaptureKit으로 동시에 캡처합니다.",
        "about.perms": "필요한 권한",
        "about.perms.body": "손쉬운 사용: 단축키를 받고 윈도우를 앞으로 가져오기 위해. 화면 기록: 제목과 미리보기를 위해.",
        "about.license": "라이선스",
        "about.license.body": "GNU 일반 공중 사용 허가서 v3.0. 자유롭게 사용, 연구, 수정, 공유할 수 있으며 파생 저작물도 같은 라이선스로 공개해야 합니다.",
        "about.source": "소스 코드",
        "about.copy": "버전 복사",
        "about.author": "디자인 및 개발",

        "layout.grid": "격자",
        "layout.filmstrip": "필름 스트립",
        "layout.coverflow": "커버 플로우",
        "layout.radial": "부채",
        "layout.book": "책",
        "layout.grid.n": "한 번에 전부. 윈도우가 많을 때 가장 읽기 좋습니다",
        "layout.filmstrip.n": "한 줄로 늘어서고, 선택한 카드가 가운데에서 커집니다",
        "layout.coverflow.n": "3D로 회전한 카드. 선택한 카드가 앞으로 나옵니다",
        "layout.radial.n": "카드가 호를 따라 배치됩니다",
        "layout.book.n": "책장을 넘기듯. 지나간 카드는 왼쪽으로 넘어갑니다",

        "motion.none": "끔",
        "motion.snappy": "경쾌하게",
        "motion.spring": "탄력 있게",
        "motion.smooth": "부드럽게",
        "motion.dramatic": "과감하게",

        "entrance.rise": "떠오르기",
        "entrance.fold": "펼치기",
        "entrance.flip": "뒤집기",
        "entrance.rise.n": "카드가 아래에서 살짝 떠오르며 또렷해집니다.",
        "entrance.fold.n": "폴더블 휴대폰이 열리듯, 카드가 왼쪽 가장자리에서 펼쳐집니다.",
        "entrance.flip.n": "카드가 자기 축을 중심으로 뒤집히며 나타납니다.",

        "material.hud": "HUD",
        "material.dark": "어둡게",
        "material.ultraThin": "얇은 유리",
        "material.sidebar": "사이드바",

        "alert.ax.title": "손쉬운 사용 권한이 필요합니다",
        "alert.ax.body": "단축키를 가로채려면 Vitrin에 손쉬운 사용 권한이 필요합니다. 허용하면 저절로 켜집니다. 그렇지 않으면 메뉴 막대에서 종료한 뒤 다시 여십시오.",
        "alert.tap.title": "키보드 이벤트를 감지할 수 없습니다",
        "alert.tap.body": "CGEvent tap을 만들지 못했습니다. 손쉬운 사용 목록에 Vitrin이 있다면 (–)로 항목을 삭제하고, 앱을 종료한 뒤 다시 열어 권한을 새로 부여하십시오.",
        "alert.openSettings": "설정 열기",
        "alert.later": "나중에",
        "alert.close": "닫기"
    ]
}